
var createFFmpegCore = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createFFmpegCore) {
  createFFmpegCore = createFFmpegCore || {};


var e;e||(e=typeof createFFmpegCore !== 'undefined' ? createFFmpegCore : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});e.quit=function(a){if(e.onExit)e.onExit(a);throw new ca(a);};e.exit=da;ea=h=function(){};var fa={},k;for(k in e)e.hasOwnProperty(k)&&(fa[k]=e[k]);var ha=[],ia="./this.program";function ja(a,b){throw b;}var ka=!1,q=!1,u=!1,la=!1;ka="object"===typeof window;q="function"===typeof importScripts;u="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;
la=!ka&&!u&&!q;var w=e.ENVIRONMENT_IS_PTHREAD||!1,x="";function ma(a){return e.locateFile?e.locateFile(a,x):x+a}var z,na,oa,B,pa;
if(u){x=q?require("path").dirname(x)+"/":__dirname+"/";z=function(a,b){B||(B=require("fs"));pa||(pa=require("path"));a=pa.normalize(a);return B.readFileSync(a,b?null:"utf8")};oa=function(a){a=z(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ia=process.argv[1].replace(/\\/g,"/"));ha=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",C);ja=function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"};
var qa;try{qa=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=qa.Worker}else if(la)"undefined"!=typeof read&&(z=function(a){return read(a)}),oa=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ha=scriptArgs:"undefined"!=typeof arguments&&(ha=arguments),
"function"===typeof quit&&(ja=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ka||q)q?x=self.location.href:"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src),_scriptDir&&(x=_scriptDir),0!==x.indexOf("blob:")?x=x.substr(0,x.lastIndexOf("/")+1):x="",u?(z=function(a,b){B||(B=require("fs"));pa||(pa=require("path"));a=pa.normalize(a);
return B.readFileSync(a,b?null:"utf8")},oa=function(a){a=z(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(z=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},q&&(oa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),na=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&
d.response?b(d.response):c()};d.onerror=c;d.send(null)});u&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var ea=e.print||console.log.bind(console),h=e.printErr||console.warn.bind(console);for(k in fa)fa.hasOwnProperty(k)&&(e[k]=fa[k]);fa=null;e.arguments&&(ha=e.arguments);e.thisProgram&&(ia=e.thisProgram);e.quit&&(ja=e.quit);var ra,sa;e.wasmBinary&&(sa=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!1;"object"!==typeof WebAssembly&&C("no native wasm support detected");
var E,ta,ua=!1;function assert(a,b){a||C("Assertion failed: "+b)}function va(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function wa(a,b,c,d){var f={string:function(n){var r=0;if(null!==n&&void 0!==n&&0!==n){var A=(n.length<<2)+1;r=xa(A);ya(n,G,r,A)}return r},array:function(n){var r=xa(n.length);H.set(n,r);return r}},g=va(a),l=[];a=0;if(d)for(var p=0;p<d.length;p++){var t=f[c[p]];t?(0===a&&(a=za()),l[p]=t(d[p])):l[p]=d[p]}c=g.apply(null,l);c=function(n){return"string"===b?I(n):"boolean"===b?!!n:n}(c);0!==a&&Aa(a);return c}
function Ba(a){var b=new TextDecoder(a);this.decode=function(c){c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var Ca="undefined"!==typeof TextDecoder?new Ba("utf8"):void 0;
function Da(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ca)return Ca.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function I(a){return a?Da(G,a,void 0):""}
function ya(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var p=a.charCodeAt(++g);l=65536+((l&1023)<<10)|p&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-f}
function Ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new Ba("utf-16le");function Fa(a){var b=Ea(a)+1,c=L(b);c&&ya(a,H,c,b);return c}function Ga(a){var b=Ea(a)+1,c=xa(b);ya(a,H,c,b);return c}function Ha(a,b,c){for(var d=0;d<a.length;++d)H[b++>>0]=a.charCodeAt(d);c||(H[b>>0]=0)}var Ia,H,G,Ja,M,N,Ka,La;w&&(Ia=e.buffer);
var Ma=e.INITIAL_MEMORY||2146435072;
if(w)E=e.wasmMemory,Ia=e.buffer;else if(e.wasmMemory)E=e.wasmMemory;else if(E=new WebAssembly.Memory({initial:Ma/65536,maximum:Ma/65536,shared:!0}),!(E.buffer instanceof SharedArrayBuffer))throw h("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),u&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),Error("bad memory");
E&&(Ia=E.buffer);Ma=Ia.byteLength;var P=Ia;Ia=P;e.HEAP8=H=new Int8Array(P);e.HEAP16=Ja=new Int16Array(P);e.HEAP32=M=new Int32Array(P);e.HEAPU8=G=new Uint8Array(P);e.HEAPU16=new Uint16Array(P);e.HEAPU32=N=new Uint32Array(P);e.HEAPF32=Ka=new Float32Array(P);e.HEAPF64=La=new Float64Array(P);var Na,Qa=[],Ra=[],Sa=[],Ta=[],Ua=[];function Va(){w||(e.noFSInit||Q.zb.dc||Q.zb(),Q.Ic=!1,Wa(Ra))}function Xa(){var a=e.preRun.shift();Qa.unshift(a)}var Ya=0,Za=null,$a=null;
function ab(){assert(!w,"addRunDependency cannot be used in a pthread worker");Ya++;e.monitorRunDependencies&&e.monitorRunDependencies(Ya)}function bb(){Ya--;e.monitorRunDependencies&&e.monitorRunDependencies(Ya);if(0==Ya&&(null!==Za&&(clearInterval(Za),Za=null),$a)){var a=$a;$a=null;a()}}e.preloadedImages={};e.preloadedAudios={};
function C(a){if(e.onAbort)e.onAbort(a);w&&console.error("Pthread aborting at "+Error().stack);h(a);ua=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function cb(){return R.startsWith("data:application/octet-stream;base64,")}var R;R="ffmpeg-core.wasm";cb()||(R=ma(R));function db(){var a=R;try{if(a==R&&sa)return new Uint8Array(sa);if(oa)return oa(a);throw"both async and sync fetching of the wasm failed";}catch(b){C(b)}}
function eb(){if(!sa&&(ka||q)){if("function"===typeof fetch&&!R.startsWith("file://"))return fetch(R,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+R+"'";return a.arrayBuffer()}).catch(function(){return db()});if(na)return new Promise(function(a,b){na(R,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return db()})}
var S,T,gb={1322624:function(){throw"Canceled!";},1322642:function(a,b){setTimeout(function(){fb(a,b)},0)}};function Wa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.ie;"number"===typeof c?void 0===b.yb?Na.get(c)():Na.get(c)(b.yb):c(void 0===b.yb?null:b.yb)}}}
function ib(a,b){if(0>=a||a>H.length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(M,kb>>2),d=0;if(c==a&&Atomics.compareExchange(M,kb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(M,a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}e._emscripten_futex_wake=ib;
function lb(a){if(w)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=U.cb[a];b&&(M[a+12>>2]=0,U.Pb(b.worker))}
var U={kb:[],jb:[],oc:[],le:function(){},sd:function(){for(var a=L(228),b=0;57>b;++b)N[a/4+b]=0;M[a+12>>2]=a;b=a+152;M[b>>2]=b;var c=L(512);for(b=0;128>b;++b)N[c/4+b]=0;Atomics.store(N,a+100>>2,c);Atomics.store(N,a+40>>2,a);mb(a,!q,1);nb(a)},td:function(){U.receiveObjectTransfer=U.Hd;U.threadInit=U.Rd;U.threadCancel=U.Pd;U.threadExit=U.Qd;U.setExitStatus=U.Ld},cb:{},Rb:[],Mc:function(){for(;0<U.Rb.length;)U.Rb.pop()();w&&V()&&ob()},Nc:function(a,b){Atomics.store(N,a+56>>2,1);Atomics.store(N,a+60>>
2,0);U.Mc();Atomics.store(N,a+4>>2,b);Atomics.store(N,a+0>>2,1);ib(a+0,2147483647);mb(0,0,0)},Ld:function(){},Qd:function(a){var b=V();b&&(U.Nc(b,a),w&&postMessage({cmd:"exit"}))},Pd:function(){U.Nc(V(),-1);postMessage({cmd:"cancelDone"})},Od:function(){for(var a in U.cb){var b=U.cb[a];b&&b.worker&&U.Pb(b.worker)}U.cb={};for(a=0;a<U.kb.length;++a){var c=U.kb[a];c.terminate()}U.kb=[];for(a=0;a<U.jb.length;++a)c=U.jb[a],b=c.Ya,U.$b(b),c.terminate();U.jb=[]},$b:function(a){if(a){if(a.eb){var b=M[a.eb+
100>>2];M[a.eb+100>>2]=0;pb(b);pb(a.eb)}a.eb=0;a.Wb&&a.qb&&pb(a.qb);a.qb=0;a.worker&&(a.worker.Ya=null)}},Pb:function(a){U.Jd(function(){delete U.cb[a.Ya.eb];U.kb.push(a);U.jb.splice(U.jb.indexOf(a),1);U.$b(a.Ya);a.Ya=void 0})},Jd:function(a){M[qb>>2]=0;try{a()}finally{M[qb>>2]=1}},Hd:function(){},Rd:function(){for(var a in U.oc)U.oc[a]()},wd:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.Ya&&(U.kd=a.Ya.eb);if(d.targetThread&&d.targetThread!=V()){var g=U.cb[d.xe];g?g.worker.postMessage(c.data,
d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===f)rb();else if("spawnThread"===f)sb(c.data);else if("cleanupThread"===f)lb(d.thread);else if("killThread"===f){c=d.thread;if(w)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";M[c+12>>2]=0;c=U.cb[c];c.worker.terminate();
U.$b(c);U.jb.splice(U.jb.indexOf(c.worker),1);c.worker.Ya=void 0}else if("cancelThread"===f){c=d.thread;if(w)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";U.cb[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===f)a.loaded=!0,b&&b(a),a.Gb&&(a.Gb(),delete a.Gb);else if("print"===f)ea("Thread "+d.threadId+": "+d.text);else if("printErr"===f)h("Thread "+d.threadId+": "+d.text);else if("alert"===
f)alert("Thread "+d.threadId+": "+d.text);else if("exit"===f)a.Ya&&Atomics.load(N,a.Ya.eb+64>>2)&&U.Pb(a);else if("exitProcess"===f)try{da(d.returnCode)}catch(l){if(l instanceof ca)return;throw l;}else"cancelDone"===f?U.Pb(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):h("worker sent an unknown command "+f));U.kd=void 0};a.onerror=function(c){h("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};u&&(a.on("message",function(c){a.onmessage({data:c})}),
a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));a.postMessage({cmd:"load",urlOrBlob:e.mainScriptUrlOrBlob||_scriptDir,wasmMemory:E,wasmModule:ta})},Xc:function(){var a=ma("ffmpeg-core.worker.js");U.kb.push(new Worker(a))},qd:function(){0==U.kb.length&&(U.Xc(),U.wd(U.kb[0]));return U.kb.pop()},$d:function(a){for(a=performance.now()+a;performance.now()<a;);}};e.establishStackSpace=function(a,b){tb(a,b);Aa(a)};e.invokeEntryPoint=function(a,b){return Na.get(a)(b)};var ub=0;
function vb(){return noExitRuntime||0<ub}e.keepRuntimeAlive=vb;var wb;u?wb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:w?wb=function(){return performance.now()-e.__performance_now_clock_drift}:"undefined"!==typeof dateNow?wb=dateNow:wb=function(){return performance.now()};function xb(a,b){U.Rb.push(function(){Na.get(a)(b)})}
function yb(a,b){a=new Date(1E3*M[a>>2]);M[b>>2]=a.getUTCSeconds();M[b+4>>2]=a.getUTCMinutes();M[b+8>>2]=a.getUTCHours();M[b+12>>2]=a.getUTCDate();M[b+16>>2]=a.getUTCMonth();M[b+20>>2]=a.getUTCFullYear()-1900;M[b+24>>2]=a.getUTCDay();M[b+36>>2]=0;M[b+32>>2]=0;M[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;yb.rc||(yb.rc=Fa("GMT"));M[b+40>>2]=yb.rc;return b}
function zb(){function a(l){return(l=l.toTimeString().match(/\(([A-Za-z ]+)\)$/))?l[1]:"GMT"}if(w)return W(1,1);if(!zb.Zc){zb.Zc=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var f=d.getTimezoneOffset(),g=Math.max(b,f);M[Ab()>>2]=60*g;M[Bb()>>2]=Number(b!=f);c=a(c);d=a(d);c=Fa(c);d=Fa(d);f<b?(M[Cb()>>2]=c,M[Cb()+4>>2]=d):(M[Cb()>>2]=d,M[Cb()+4>>2]=c)}}
function Db(a,b){zb();a=new Date(1E3*M[a>>2]);M[b>>2]=a.getSeconds();M[b+4>>2]=a.getMinutes();M[b+8>>2]=a.getHours();M[b+12>>2]=a.getDate();M[b+16>>2]=a.getMonth();M[b+20>>2]=a.getFullYear()-1900;M[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);M[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;M[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;M[b+32>>2]=a;a=M[Cb()+(a?4:0)>>2];
M[b+40>>2]=a;return b}function Eb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Fb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Eb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Gb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function X(a){if("/"===a)return"/";a=Fb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Hb(a,b){return Fb(a+"/"+b)}
function Ib(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(u)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){C("randomDevice")}}
function Jb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:Q.cwd();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Eb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}
function Kb(a,b){function c(l){for(var p=0;p<l.length&&""===l[p];p++);for(var t=l.length-1;0<=t&&""===l[t];t--);return p>t?[]:l.slice(p,t-p+1)}a=Jb(a).substr(1);b=Jb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")}var Lb=[];function Mb(a,b){Lb[a]={input:[],output:[],tb:b};Q.nc(a,Nb)}
var Nb={open:function(a){var b=Lb[a.node.rdev];if(!b)throw new Q.Ka(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.tb.flush(a.tty)},flush:function(a){a.tty.tb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.tb.Ec)throw new Q.Ka(60);for(var f=0,g=0;g<d;g++){try{var l=a.tty.tb.Ec(a.tty)}catch(p){throw new Q.Ka(29);}if(void 0===l&&0===f)throw new Q.Ka(6);if(null===l||void 0===l)break;f++;b[c+g]=l}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.tb.kc)throw new Q.Ka(60);
try{for(var f=0;f<d;f++)a.tty.tb.kc(a.tty,b[c+f])}catch(g){throw new Q.Ka(29);}d&&(a.node.timestamp=Date.now());return f}},Pb={Ec:function(a){if(!a.input.length){var b=null;if(u){var c=Buffer.rb?Buffer.rb(256):new Buffer(256),d=0;try{d=B.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(f.toString().includes("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Ob(b,!0)}return a.input.shift()},kc:function(a,b){null===b||10===b?(ea(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ea(Da(a.output,0)),a.output=[])}},Qb={kc:function(a,b){null===b||10===b?(h(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(Da(a.output,0)),a.output=[])}},Y={bb:null,Ra:function(){return Y.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(Q.ud(c)||Q.isFIFO(c))throw new Q.Ka(63);Y.bb||(Y.bb={dir:{node:{Za:Y.La.Za,Ua:Y.La.Ua,lookup:Y.La.lookup,fb:Y.La.fb,rename:Y.La.rename,unlink:Y.La.unlink,rmdir:Y.La.rmdir,readdir:Y.La.readdir,symlink:Y.La.symlink},stream:{Wa:Y.Na.Wa}},file:{node:{Za:Y.La.Za,Ua:Y.La.Ua},stream:{Wa:Y.Na.Wa,read:Y.Na.read,write:Y.Na.write,xb:Y.Na.xb,Cb:Y.Na.Cb,Fb:Y.Na.Fb}},link:{node:{Za:Y.La.Za,Ua:Y.La.Ua,readlink:Y.La.readlink},stream:{}},tc:{node:{Za:Y.La.Za,Ua:Y.La.Ua},
stream:Q.ad}});c=Q.createNode(a,b,c,d);Q.Sa(c.mode)?(c.La=Y.bb.dir.node,c.Na=Y.bb.dir.stream,c.Ma={}):Q.isFile(c.mode)?(c.La=Y.bb.file.node,c.Na=Y.bb.file.stream,c.Qa=0,c.Ma=null):Q.mb(c.mode)?(c.La=Y.bb.link.node,c.Na=Y.bb.link.stream):Q.Ab(c.mode)&&(c.La=Y.bb.tc.node,c.Na=Y.bb.tc.stream);c.timestamp=Date.now();a&&(a.Ma[b]=c,a.timestamp=c.timestamp);return c},je:function(a){return a.Ma?a.Ma.subarray?a.Ma.subarray(0,a.Qa):new Uint8Array(a.Ma):new Uint8Array(0)},zc:function(a,b){var c=a.Ma?a.Ma.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ma,a.Ma=new Uint8Array(b),0<a.Qa&&a.Ma.set(c.subarray(0,a.Qa),0))},Id:function(a,b){if(a.Qa!=b)if(0==b)a.Ma=null,a.Qa=0;else{var c=a.Ma;a.Ma=new Uint8Array(b);c&&a.Ma.set(c.subarray(0,Math.min(b,a.Qa)));a.Qa=b}},La:{Za:function(a){var b={};b.dev=Q.Ab(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;Q.Sa(a.mode)?b.size=4096:Q.isFile(a.mode)?b.size=a.Qa:Q.mb(a.mode)?b.size=a.link.length:b.size=
0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Yc=4096;b.blocks=Math.ceil(b.size/b.Yc);return b},Ua:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&Y.Id(a,b.size)},lookup:function(){throw Q.ac[44];},fb:function(a,b,c,d){return Y.createNode(a,b,c,d)},rename:function(a,b,c){if(Q.Sa(a.mode)){try{var d=Q.$a(b,c)}catch(g){}if(d)for(var f in d.Ma)throw new Q.Ka(55);}delete a.parent.Ma[a.name];
a.parent.timestamp=Date.now();a.name=c;b.Ma[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Ma[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=Q.$a(a,b),d;for(d in c.Ma)throw new Q.Ka(55);delete a.Ma[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Ma)a.Ma.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=Y.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!Q.mb(a.mode))throw new Q.Ka(28);return a.link}},
Na:{read:function(a,b,c,d,f){var g=a.node.Ma;if(f>=a.node.Qa)return 0;a=Math.min(a.node.Qa-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ma||a.Ma.subarray)){if(g)return a.Ma=b.subarray(c,c+d),a.Qa=d;if(0===a.Qa&&0===f)return a.Ma=b.slice(c,c+d),a.Qa=d;if(f+d<=a.Qa)return a.Ma.set(b.subarray(c,c+d),f),d}Y.zc(a,f+d);if(a.Ma.subarray&&b.subarray)a.Ma.set(b.subarray(c,
c+d),f);else for(g=0;g<d;g++)a.Ma[f+g]=b[c+g];a.Qa=Math.max(a.Qa,f+d);return d},Wa:function(a,b,c){1===c?b+=a.position:2===c&&Q.isFile(a.node.mode)&&(b+=a.node.Qa);if(0>b)throw new Q.Ka(28);return b},xb:function(a,b,c){Y.zc(a.node,b+c);a.node.Qa=Math.max(a.node.Qa,b+c)},Cb:function(a,b,c,d,f,g){if(0!==b)throw new Q.Ka(28);if(!Q.isFile(a.node.mode))throw new Q.Ka(43);a=a.node.Ma;if(g&2||a.buffer!==Ia){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=
65536*Math.ceil(c/65536);for(b=L(g);c<g;)H[b+c++]=0;c=b;if(!c)throw new Q.Ka(48);H.set(a,c)}else d=!1,c=a.byteOffset;return{ue:c,Yd:d}},Fb:function(a,b,c,d,f){if(!Q.isFile(a.node.mode))throw new Q.Ka(43);if(f&2)return 0;Y.Na.write(a,b,0,d,c,!1);return 0}}},Q={root:null,Eb:[],wc:{},streams:[],Bd:1,ab:null,vc:"/",dc:!1,Ic:!0,Ta:{},Pc:{Lc:{Tc:1,Uc:2}},Ka:null,ac:{},nd:null,Qb:0,Pa:function(a,b){a=Jb(Q.cwd(),a);b=b||{};if(!a)return{path:"",node:null};var c={Zb:!0,mc:0},d;for(d in c)void 0===b[d]&&(b[d]=
c[d]);if(8<b.mc)throw new Q.Ka(32);a=Eb(a.split("/").filter(function(l){return!!l}),!1);var f=Q.root;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=Q.$a(f,a[d]);c=Hb(c,a[d]);Q.nb(f)&&(!g||g&&b.Zb)&&(f=f.Db.root);if(!g||b.Xa)for(g=0;Q.mb(f.mode);)if(f=Q.readlink(c),c=Jb(Gb(c),f),f=Q.Pa(c,{mc:b.mc}).node,40<g++)throw new Q.Ka(32);}return{path:c,node:f}},hb:function(a){for(var b;;){if(Q.Lb(a))return a=a.Ra.Jc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},
cc:function(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Q.ab.length},Gc:function(a){var b=Q.cc(a.parent.id,a.name);a.pb=Q.ab[b];Q.ab[b]=a},Hc:function(a){var b=Q.cc(a.parent.id,a.name);if(Q.ab[b]===a)Q.ab[b]=a.pb;else for(b=Q.ab[b];b;){if(b.pb===a){b.pb=a.pb;break}b=b.pb}},$a:function(a,b){var c=Q.yd(a);if(c)throw new Q.Ka(c,a);for(c=Q.ab[Q.cc(a.id,b)];c;c=c.pb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return Q.lookup(a,b)},createNode:function(a,b,c,
d){a=new Q.Qc(a,b,c,d);Q.Gc(a);return a},Yb:function(a){Q.Hc(a)},Lb:function(a){return a===a.parent},nb:function(a){return!!a.Db},isFile:function(a){return 32768===(a&61440)},Sa:function(a){return 16384===(a&61440)},mb:function(a){return 40960===(a&61440)},Ab:function(a){return 8192===(a&61440)},ud:function(a){return 24576===(a&61440)},isFIFO:function(a){return 4096===(a&61440)},isSocket:function(a){return 49152===(a&49152)},od:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Ad:function(a){var b=Q.od[a];
if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},Ac:function(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},ib:function(a,b){if(Q.Ic)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},yd:function(a){var b=Q.ib(a,"x");return b?b:a.La.lookup?0:2},jc:function(a,b){try{return Q.$a(a,b),20}catch(c){}return Q.ib(a,"wx")},Mb:function(a,b,c){try{var d=Q.$a(a,b)}catch(f){return f.Oa}if(a=
Q.ib(a,"wx"))return a;if(c){if(!Q.Sa(d.mode))return 54;if(Q.Lb(d)||Q.hb(d)===Q.cwd())return 10}else if(Q.Sa(d.mode))return 31;return 0},zd:function(a,b){return a?Q.mb(a.mode)?32:Q.Sa(a.mode)&&("r"!==Q.Ac(b)||b&512)?31:Q.ib(a,Q.Ac(b)):44},Sc:4096,Cd:function(a,b){b=b||Q.Sc;for(a=a||0;a<=b;a++)if(!Q.streams[a])return a;throw new Q.Ka(33);},sb:function(a){return Q.streams[a]},jd:function(a,b,c){Q.Vb||(Q.Vb=function(){},Q.Vb.prototype={object:{get:function(){return this.node},set:function(g){this.node=
g}}});var d=new Q.Vb,f;for(f in a)d[f]=a[f];a=d;b=Q.Cd(b,c);a.fd=b;return Q.streams[b]=a},bd:function(a){Q.streams[a]=null},ad:{open:function(a){a.Na=Q.pd(a.node.rdev).Na;a.Na.open&&a.Na.open(a)},Wa:function(){throw new Q.Ka(70);}},ic:function(a){return a>>8},ne:function(a){return a&255},ob:function(a,b){return a<<8|b},nc:function(a,b){Q.wc[a]={Na:b}},pd:function(a){return Q.wc[a]},Dc:function(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.Eb)}return b},Oc:function(a,b){function c(l){Q.Qb--;
return b(l)}function d(l){if(l){if(!d.ld)return d.ld=!0,c(l)}else++g>=f.length&&c(null)}"function"===typeof a&&(b=a,a=!1);Q.Qb++;1<Q.Qb&&h("warning: "+Q.Qb+" FS.syncfs operations in flight at once, probably just doing extra work");var f=Q.Dc(Q.root.Ra),g=0;f.forEach(function(l){if(!l.type.Oc)return d(null);l.type.Oc(l,a,d)})},Ra:function(a,b,c){var d="/"===c,f=!c;if(d&&Q.root)throw new Q.Ka(10);if(!d&&!f){var g=Q.Pa(c,{Zb:!1});c=g.path;g=g.node;if(Q.nb(g))throw new Q.Ka(10);if(!Q.Sa(g.mode))throw new Q.Ka(54);
}b={type:a,se:b,Jc:c,Eb:[]};a=a.Ra(b);a.Ra=b;b.root=a;d?Q.root=a:g&&(g.Db=b,g.Ra&&g.Ra.Eb.push(b));return a},ze:function(a){a=Q.Pa(a,{Zb:!1});if(!Q.nb(a.node))throw new Q.Ka(28);a=a.node;var b=a.Db,c=Q.Dc(b);Object.keys(Q.ab).forEach(function(d){for(d=Q.ab[d];d;){var f=d.pb;c.includes(d.Ra)&&Q.Yb(d);d=f}});a.Db=null;a.Ra.Eb.splice(a.Ra.Eb.indexOf(b),1)},lookup:function(a,b){return a.La.lookup(a,b)},fb:function(a,b,c){var d=Q.Pa(a,{parent:!0}).node;a=X(a);if(!a||"."===a||".."===a)throw new Q.Ka(28);
var f=Q.jc(d,a);if(f)throw new Q.Ka(f);if(!d.La.fb)throw new Q.Ka(63);return d.La.fb(d,a,b,c)},create:function(a,b){return Q.fb(a,(void 0!==b?b:438)&4095|32768,0)},mkdir:function(a,b){return Q.fb(a,(void 0!==b?b:511)&1023|16384,0)},pe:function(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{Q.mkdir(c,b)}catch(f){if(20!=f.Oa)throw f;}}},Nb:function(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Q.fb(a,b|8192,c)},symlink:function(a,b){if(!Jb(a))throw new Q.Ka(44);var c=
Q.Pa(b,{parent:!0}).node;if(!c)throw new Q.Ka(44);b=X(b);var d=Q.jc(c,b);if(d)throw new Q.Ka(d);if(!c.La.symlink)throw new Q.Ka(63);return c.La.symlink(c,b,a)},rename:function(a,b){var c=Gb(a),d=Gb(b),f=X(a),g=X(b);var l=Q.Pa(a,{parent:!0});var p=l.node;l=Q.Pa(b,{parent:!0});l=l.node;if(!p||!l)throw new Q.Ka(44);if(p.Ra!==l.Ra)throw new Q.Ka(75);var t=Q.$a(p,f);d=Kb(a,d);if("."!==d.charAt(0))throw new Q.Ka(28);d=Kb(b,c);if("."!==d.charAt(0))throw new Q.Ka(55);try{var n=Q.$a(l,g)}catch(r){}if(t!==
n){c=Q.Sa(t.mode);if(f=Q.Mb(p,f,c))throw new Q.Ka(f);if(f=n?Q.Mb(l,g,c):Q.jc(l,g))throw new Q.Ka(f);if(!p.La.rename)throw new Q.Ka(63);if(Q.nb(t)||n&&Q.nb(n))throw new Q.Ka(10);if(l!==p&&(f=Q.ib(p,"w")))throw new Q.Ka(f);try{Q.Ta.willMovePath&&Q.Ta.willMovePath(a,b)}catch(r){h("FS.trackingDelegate['willMovePath']('"+a+"', '"+b+"') threw an exception: "+r.message)}Q.Hc(t);try{p.La.rename(t,l,g)}catch(r){throw r;}finally{Q.Gc(t)}try{if(Q.Ta.onMovePath)Q.Ta.onMovePath(a,b)}catch(r){h("FS.trackingDelegate['onMovePath']('"+
a+"', '"+b+"') threw an exception: "+r.message)}}},rmdir:function(a){var b=Q.Pa(a,{parent:!0}).node,c=X(a),d=Q.$a(b,c),f=Q.Mb(b,c,!0);if(f)throw new Q.Ka(f);if(!b.La.rmdir)throw new Q.Ka(63);if(Q.nb(d))throw new Q.Ka(10);try{Q.Ta.willDeletePath&&Q.Ta.willDeletePath(a)}catch(g){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.La.rmdir(b,c);Q.Yb(d);try{if(Q.Ta.onDeletePath)Q.Ta.onDeletePath(a)}catch(g){h("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+
g.message)}},readdir:function(a){a=Q.Pa(a,{Xa:!0}).node;if(!a.La.readdir)throw new Q.Ka(54);return a.La.readdir(a)},unlink:function(a){var b=Q.Pa(a,{parent:!0}).node,c=X(a),d=Q.$a(b,c),f=Q.Mb(b,c,!1);if(f)throw new Q.Ka(f);if(!b.La.unlink)throw new Q.Ka(63);if(Q.nb(d))throw new Q.Ka(10);try{Q.Ta.willDeletePath&&Q.Ta.willDeletePath(a)}catch(g){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.La.unlink(b,c);Q.Yb(d);try{if(Q.Ta.onDeletePath)Q.Ta.onDeletePath(a)}catch(g){h("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+g.message)}},readlink:function(a){a=Q.Pa(a).node;if(!a)throw new Q.Ka(44);if(!a.La.readlink)throw new Q.Ka(28);return Jb(Q.hb(a.parent),a.La.readlink(a))},stat:function(a,b){a=Q.Pa(a,{Xa:!b}).node;if(!a)throw new Q.Ka(44);if(!a.La.Za)throw new Q.Ka(63);return a.La.Za(a)},lstat:function(a){return Q.stat(a,!0)},chmod:function(a,b,c){a="string"===typeof a?Q.Pa(a,{Xa:!c}).node:a;if(!a.La.Ua)throw new Q.Ka(63);a.La.Ua(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:function(a,
b){Q.chmod(a,b,!0)},fchmod:function(a,b){a=Q.sb(a);if(!a)throw new Q.Ka(8);Q.chmod(a.node,b)},chown:function(a,b,c,d){a="string"===typeof a?Q.Pa(a,{Xa:!d}).node:a;if(!a.La.Ua)throw new Q.Ka(63);a.La.Ua(a,{timestamp:Date.now()})},lchown:function(a,b,c){Q.chown(a,b,c,!0)},fchown:function(a,b,c){a=Q.sb(a);if(!a)throw new Q.Ka(8);Q.chown(a.node,b,c)},truncate:function(a,b){if(0>b)throw new Q.Ka(28);a="string"===typeof a?Q.Pa(a,{Xa:!0}).node:a;if(!a.La.Ua)throw new Q.Ka(63);if(Q.Sa(a.mode))throw new Q.Ka(31);
if(!Q.isFile(a.mode))throw new Q.Ka(28);var c=Q.ib(a,"w");if(c)throw new Q.Ka(c);a.La.Ua(a,{size:b,timestamp:Date.now()})},he:function(a,b){a=Q.sb(a);if(!a)throw new Q.Ka(8);if(0===(a.flags&2097155))throw new Q.Ka(28);Q.truncate(a.node,b)},Ae:function(a,b,c){a=Q.Pa(a,{Xa:!0}).node;a.La.Ua(a,{timestamp:Math.max(b,c)})},open:function(a,b,c,d,f){if(""===a)throw new Q.Ka(44);b="string"===typeof b?Q.Ad(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Fb(a);
try{g=Q.Pa(a,{Xa:!(b&131072)}).node}catch(p){}}var l=!1;if(b&64)if(g){if(b&128)throw new Q.Ka(20);}else g=Q.fb(a,c,0),l=!0;if(!g)throw new Q.Ka(44);Q.Ab(g.mode)&&(b&=-513);if(b&65536&&!Q.Sa(g.mode))throw new Q.Ka(54);if(!l&&(c=Q.zd(g,b)))throw new Q.Ka(c);b&512&&Q.truncate(g,0);b&=-131713;d=Q.jd({node:g,path:Q.hb(g),flags:b,seekable:!0,position:0,Na:g.Na,Xd:[],error:!1},d,f);d.Na.open&&d.Na.open(d);!e.logReadFiles||b&1||(Q.lc||(Q.lc={}),a in Q.lc||(Q.lc[a]=1,h("FS.trackingDelegate error on read file: "+
a)));try{Q.Ta.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=Q.Pc.Lc.Tc),0!==(b&2097155)&&(f|=Q.Pc.Lc.Uc),Q.Ta.onOpenFile(a,f))}catch(p){h("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+p.message)}return d},close:function(a){if(Q.Bb(a))throw new Q.Ka(8);a.lb&&(a.lb=null);try{a.Na.close&&a.Na.close(a)}catch(b){throw b;}finally{Q.bd(a.fd)}a.fd=null},Bb:function(a){return null===a.fd},Wa:function(a,b,c){if(Q.Bb(a))throw new Q.Ka(8);if(!a.seekable||!a.Na.Wa)throw new Q.Ka(70);if(0!=c&&
1!=c&&2!=c)throw new Q.Ka(28);a.position=a.Na.Wa(a,b,c);a.Xd=[];return a.position},read:function(a,b,c,d,f){if(0>d||0>f)throw new Q.Ka(28);if(Q.Bb(a))throw new Q.Ka(8);if(1===(a.flags&2097155))throw new Q.Ka(8);if(Q.Sa(a.node.mode))throw new Q.Ka(31);if(!a.Na.read)throw new Q.Ka(28);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new Q.Ka(70);b=a.Na.read(a,b,c,d,f);g||(a.position+=b);return b},write:function(a,b,c,d,f,g){if(0>d||0>f)throw new Q.Ka(28);if(Q.Bb(a))throw new Q.Ka(8);
if(0===(a.flags&2097155))throw new Q.Ka(8);if(Q.Sa(a.node.mode))throw new Q.Ka(31);if(!a.Na.write)throw new Q.Ka(28);a.seekable&&a.flags&1024&&Q.Wa(a,0,2);var l="undefined"!==typeof f;if(!l)f=a.position;else if(!a.seekable)throw new Q.Ka(70);b=a.Na.write(a,b,c,d,f,g);l||(a.position+=b);try{if(a.path&&Q.Ta.onWriteToFile)Q.Ta.onWriteToFile(a.path)}catch(p){h("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+p.message)}return b},xb:function(a,b,c){if(Q.Bb(a))throw new Q.Ka(8);
if(0>b||0>=c)throw new Q.Ka(28);if(0===(a.flags&2097155))throw new Q.Ka(8);if(!Q.isFile(a.node.mode)&&!Q.Sa(a.node.mode))throw new Q.Ka(43);if(!a.Na.xb)throw new Q.Ka(138);a.Na.xb(a,b,c)},Cb:function(a,b,c,d,f,g){if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new Q.Ka(2);if(1===(a.flags&2097155))throw new Q.Ka(2);if(!a.Na.Cb)throw new Q.Ka(43);return a.Na.Cb(a,b,c,d,f,g)},Fb:function(a,b,c,d,f){return a&&a.Na.Fb?a.Na.Fb(a,b,c,d,f):0},re:function(){return 0},ec:function(a,b,c){if(!a.Na.ec)throw new Q.Ka(59);
return a.Na.ec(a,b,c)},readFile:function(a,b){b=b||{};b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,d=Q.open(a,b.flags);a=Q.stat(a).size;var f=new Uint8Array(a);Q.read(d,f,0,a,0);"utf8"===b.encoding?c=Da(f,0):"binary"===b.encoding&&(c=f);Q.close(d);return c},writeFile:function(a,b,c){c=c||{};c.flags=c.flags||577;a=Q.open(a,c.flags,c.mode);if("string"===typeof b){var d=new Uint8Array(Ea(b)+
1);b=ya(b,d,0,d.length);Q.write(a,d,0,b,void 0,c.$c)}else if(ArrayBuffer.isView(b))Q.write(a,b,0,b.byteLength,void 0,c.$c);else throw Error("Unsupported data type");Q.close(a)},cwd:function(){return Q.vc},chdir:function(a){a=Q.Pa(a,{Xa:!0});if(null===a.node)throw new Q.Ka(44);if(!Q.Sa(a.node.mode))throw new Q.Ka(54);var b=Q.ib(a.node,"x");if(b)throw new Q.Ka(b);Q.vc=a.path},dd:function(){Q.mkdir("/tmp");Q.mkdir("/home");Q.mkdir("/home/web_user")},cd:function(){Q.mkdir("/dev");Q.nc(Q.ob(1,3),{read:function(){return 0},
write:function(b,c,d,f){return f}});Q.Nb("/dev/null",Q.ob(1,3));Mb(Q.ob(5,0),Pb);Mb(Q.ob(6,0),Qb);Q.Nb("/dev/tty",Q.ob(5,0));Q.Nb("/dev/tty1",Q.ob(6,0));var a=Ib();Q.gb("/dev","random",a);Q.gb("/dev","urandom",a);Q.mkdir("/dev/shm");Q.mkdir("/dev/shm/tmp")},gd:function(){Q.mkdir("/proc");var a=Q.mkdir("/proc/self");Q.mkdir("/proc/self/fd");Q.Ra({Ra:function(){var b=Q.createNode(a,"fd",16895,73);b.La={lookup:function(c,d){var f=Q.sb(+d);if(!f)throw new Q.Ka(8);c={parent:null,Ra:{Jc:"fake"},La:{readlink:function(){return f.path}}};
return c.parent=c}};return b}},{},"/proc/self/fd")},hd:function(){e.stdin?Q.gb("/dev","stdin",e.stdin):Q.symlink("/dev/tty","/dev/stdin");e.stdout?Q.gb("/dev","stdout",null,e.stdout):Q.symlink("/dev/tty","/dev/stdout");e.stderr?Q.gb("/dev","stderr",null,e.stderr):Q.symlink("/dev/tty1","/dev/stderr");Q.open("/dev/stdin",0);Q.open("/dev/stdout",1);Q.open("/dev/stderr",1)},yc:function(){Q.Ka||(Q.Ka=function(a,b){this.node=b;this.Kd=function(c){this.Oa=c};this.Kd(a);this.message="FS error"},Q.Ka.prototype=
Error(),Q.Ka.prototype.constructor=Q.Ka,[44].forEach(function(a){Q.ac[a]=new Q.Ka(a);Q.ac[a].stack="<generic error, no stack>"}))},Nd:function(){Q.yc();Q.ab=Array(4096);Q.Ra(Y,{},"/");Q.dd();Q.cd();Q.gd();Q.nd={MEMFS:Y}},zb:function(a,b,c){Q.zb.dc=!0;Q.yc();e.stdin=a||e.stdin;e.stdout=b||e.stdout;e.stderr=c||e.stderr;Q.hd()},quit:function(){Q.zb.dc=!1;var a=e._fflush;a&&a(0);for(a=0;a<Q.streams.length;a++){var b=Q.streams[a];b&&Q.close(b)}},bc:function(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c},
ge:function(a,b){a=Q.Xb(a,b);return a.exists?a.object:null},Xb:function(a,b){try{var c=Q.Pa(a,{Xa:!b});a=c.path}catch(f){}var d={Lb:!1,exists:!1,error:0,name:null,path:null,object:null,Dd:!1,Fd:null,Ed:null};try{c=Q.Pa(a,{parent:!0}),d.Dd=!0,d.Fd=c.path,d.Ed=c.node,d.name=X(a),c=Q.Pa(a,{Xa:!b}),d.exists=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.Lb="/"===c.path}catch(f){d.error=f.Oa}return d},de:function(a,b){a="string"===typeof a?a:Q.hb(a);for(b=b.split("/").reverse();b.length;){var c=
b.pop();if(c){var d=Hb(a,c);try{Q.mkdir(d)}catch(f){}a=d}}return d},ed:function(a,b,c,d,f){a=Hb("string"===typeof a?a:Q.hb(a),b);return Q.create(a,Q.bc(d,f))},uc:function(a,b,c,d,f,g){a=b?Hb("string"===typeof a?a:Q.hb(a),b):a;d=Q.bc(d,f);f=Q.create(a,d);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var l=c.length;b<l;++b)a[b]=c.charCodeAt(b);c=a}Q.chmod(f,d|146);a=Q.open(f,577);Q.write(a,c,0,c.length,0,g);Q.close(a);Q.chmod(f,d)}return f},gb:function(a,b,c,d){a=Hb("string"===typeof a?a:
Q.hb(a),b);b=Q.bc(!!c,!!d);Q.gb.ic||(Q.gb.ic=64);var f=Q.ob(Q.gb.ic++,0);Q.nc(f,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,l,p,t){for(var n=0,r=0;r<t;r++){try{var A=c()}catch(F){throw new Q.Ka(29);}if(void 0===A&&0===n)throw new Q.Ka(6);if(null===A||void 0===A)break;n++;l[p+r]=A}n&&(g.node.timestamp=Date.now());return n},write:function(g,l,p,t){for(var n=0;n<t;n++)try{d(l[p+n])}catch(r){throw new Q.Ka(29);}t&&(g.node.timestamp=Date.now());
return n}});return Q.Nb(a,b,f)},Bc:function(a){if(a.fc||a.vd||a.link||a.Ma)return!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(z)try{a.Ma=Ob(z(a.url),!0),a.Qa=a.Ma.length}catch(b){throw new Q.Ka(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},ce:function(a,b,c,d,f){function g(){this.hc=
!1;this.rb=[]}g.prototype.get=function(n){if(!(n>this.length-1||0>n)){var r=n%this.chunkSize;return this.Fc(n/this.chunkSize|0)[r]}};g.prototype.Rc=function(n){this.Fc=n};g.prototype.sc=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var r=Number(n.getResponseHeader("Content-length")),A,F=(A=n.getResponseHeader("Accept-Ranges"))&&"bytes"===A;n=(A=n.getResponseHeader("Content-Encoding"))&&
"gzip"===A;var m=1048576;F||(m=r);var v=this;v.Rc(function(y){var J=y*m,O=(y+1)*m-1;O=Math.min(O,r-1);if("undefined"===typeof v.rb[y]){var hb=v.rb;if(J>O)throw Error("invalid range ("+J+", "+O+") or no bytes requested!");if(O>r-1)throw Error("only "+r+" bytes available! programmer error!");var D=new XMLHttpRequest;D.open("GET",c,!1);r!==m&&D.setRequestHeader("Range","bytes="+J+"-"+O);"undefined"!=typeof Uint8Array&&(D.responseType="arraybuffer");D.overrideMimeType&&D.overrideMimeType("text/plain; charset=x-user-defined");
D.send(null);if(!(200<=D.status&&300>D.status||304===D.status))throw Error("Couldn't load "+c+". Status: "+D.status);J=void 0!==D.response?new Uint8Array(D.response||[]):Ob(D.responseText||"",!0);hb[y]=J}if("undefined"===typeof v.rb[y])throw Error("doXHR failed!");return v.rb[y]});if(n||!r)m=r=1,m=r=this.Fc(0).length,ea("LazyFiles on gzip forces download of the whole file when length is accessed");this.Wc=r;this.Vc=m;this.hc=!0};if("undefined"!==typeof XMLHttpRequest){if(!q)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var l=new g;Object.defineProperties(l,{length:{get:function(){this.hc||this.sc();return this.Wc}},chunkSize:{get:function(){this.hc||this.sc();return this.Vc}}});l={fc:!1,Ma:l}}else l={fc:!1,url:c};var p=Q.ed(a,b,l,d,f);l.Ma?p.Ma=l.Ma:l.url&&(p.Ma=null,p.url=l.url);Object.defineProperties(p,{Qa:{get:function(){return this.Ma.length}}});var t={};Object.keys(p.Na).forEach(function(n){var r=p.Na[n];t[n]=function(){Q.Bc(p);return r.apply(null,arguments)}});t.read=function(n,r,A,F,m){Q.Bc(p);n=n.node.Ma;
if(m>=n.length)return 0;F=Math.min(n.length-m,F);if(n.slice)for(var v=0;v<F;v++)r[A+v]=n[m+v];else for(v=0;v<F;v++)r[A+v]=n.get(m+v);return F};p.Na=t;return p},ee:function(a,b,c,d,f,g,l,p,t,n){function r(F){function m(y){n&&n();p||Q.uc(a,b,y,d,f,t);g&&g();bb()}var v=!1;e.preloadPlugins.forEach(function(y){!v&&y.canHandle(A)&&(y.handle(F,A,m,function(){l&&l();bb()}),v=!0)});v||m(F)}Rb.zb();var A=b?Jb(Hb(a,b)):a;ab();"string"==typeof c?Rb.Zd(c,function(F){r(F)},l):r(c)},indexedDB:function(){return window.indexedDB||
window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},pc:function(){return"EM_FS_"+window.location.pathname},qc:20,wb:"FILE_DATA",we:function(a,b,c){b=b||function(){};c=c||function(){};var d=Q.indexedDB();try{var f=d.open(Q.pc(),Q.qc)}catch(g){return c(g)}f.onupgradeneeded=function(){ea("creating db");f.result.createObjectStore(Q.wb)};f.onsuccess=function(){var g=f.result.transaction([Q.wb],"readwrite"),l=g.objectStore(Q.wb),p=0,t=0,n=a.length;a.forEach(function(r){r=l.put(Q.Xb(r).object.Ma,
r);r.onsuccess=function(){p++;p+t==n&&(0==t?b():c())};r.onerror=function(){t++;p+t==n&&(0==t?b():c())}});g.onerror=c};f.onerror=c},me:function(a,b,c){b=b||function(){};c=c||function(){};var d=Q.indexedDB();try{var f=d.open(Q.pc(),Q.qc)}catch(g){return c(g)}f.onupgradeneeded=c;f.onsuccess=function(){var g=f.result;try{var l=g.transaction([Q.wb],"readonly")}catch(A){c(A);return}var p=l.objectStore(Q.wb),t=0,n=0,r=a.length;a.forEach(function(A){var F=p.get(A);F.onsuccess=function(){Q.Xb(A).exists&&Q.unlink(A);
Q.uc(Gb(A),X(A),F.result,!0,!0,!0);t++;t+n==r&&(0==n?b():c())};F.onerror=function(){n++;t+n==r&&(0==n?b():c())}});l.onerror=c};f.onerror=c}};
function Sb(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&Fb(b)!==Fb(Q.hb(f.node)))return-54;throw f;}M[c>>2]=d.dev;M[c+4>>2]=0;M[c+8>>2]=d.ino;M[c+12>>2]=d.mode;M[c+16>>2]=d.nlink;M[c+20>>2]=d.uid;M[c+24>>2]=d.gid;M[c+28>>2]=d.rdev;M[c+32>>2]=0;T=[d.size>>>0,(S=d.size,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];M[c+40>>2]=T[0];M[c+44>>2]=T[1];M[c+48>>2]=4096;M[c+52>>2]=d.blocks;M[c+56>>2]=d.atime.getTime()/1E3|0;M[c+60>>
2]=0;M[c+64>>2]=d.mtime.getTime()/1E3|0;M[c+68>>2]=0;M[c+72>>2]=d.ctime.getTime()/1E3|0;M[c+76>>2]=0;T=[d.ino>>>0,(S=d.ino,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];M[c+80>>2]=T[0];M[c+84>>2]=T[1];return 0}var Tb=void 0;function Ub(){Tb+=4;return M[Tb-4>>2]}function Z(a){a=Q.sb(a);if(!a)throw new Q.Ka(8);return a}
function Vb(a,b,c,d,f){if(w)return W(2,1,a,b,c,d,f);try{f=0;for(var g=b?M[b>>2]:0,l=b?M[b+4>>2]:0,p=c?M[c>>2]:0,t=c?M[c+4>>2]:0,n=d?M[d>>2]:0,r=d?M[d+4>>2]:0,A=0,F=0,m=0,v=0,y=0,J=0,O=(b?M[b>>2]:0)|(c?M[c>>2]:0)|(d?M[d>>2]:0),hb=(b?M[b+4>>2]:0)|(c?M[c+4>>2]:0)|(d?M[d+4>>2]:0),D=0;D<a;D++){var K=1<<D%32;if(32>D?O&K:hb&K){var Oa=Q.sb(D);if(!Oa)throw new Q.Ka(8);var Pa=5;Oa.Na.Gd&&(Pa=Oa.Na.Gd(Oa));Pa&1&&(32>D?g&K:l&K)&&(32>D?A|=K:F|=K,f++);Pa&4&&(32>D?p&K:t&K)&&(32>D?m|=K:v|=K,f++);Pa&2&&(32>D?n&K:
r&K)&&(32>D?y|=K:J|=K,f++)}}b&&(M[b>>2]=A,M[b+4>>2]=F);c&&(M[c>>2]=m,M[c+4>>2]=v);d&&(M[d>>2]=y,M[d+4>>2]=J);return f}catch(jb){return"undefined"!==typeof Q&&jb instanceof Q.Ka||C(jb),-jb.Oa}}function Wb(a,b){if(w)return W(3,1,a,b);try{a=I(a);if(b&-8)var c=-28;else{var d;(d=Q.Pa(a,{Xa:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&Q.ib(d,a)?-2:0):c=-44}return c}catch(f){return"undefined"!==typeof Q&&f instanceof Q.Ka||C(f),-f.Oa}}
function Xb(a,b,c){if(w)return W(4,1,a,b,c);Tb=c;try{var d=Z(a);switch(b){case 0:var f=Ub();return 0>f?-28:Q.open(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=Ub(),d.flags|=f,0;case 12:return f=Ub(),Ja[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return M[Yb()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof Q&&g instanceof Q.Ka||C(g),-g.Oa}}
function Zb(a,b){if(w)return W(5,1,a,b);try{var c=Z(a);return Sb(Q.stat,c.path,b)}catch(d){return"undefined"!==typeof Q&&d instanceof Q.Ka||C(d),-d.Oa}}
function $b(a,b,c){if(w)return W(6,1,a,b,c);try{var d=Z(a);d.lb||(d.lb=Q.readdir(d.path));a=0;for(var f=Q.Wa(d,0,1),g=Math.floor(f/280);g<d.lb.length&&a+280<=c;){var l=d.lb[g];if("."===l[0]){var p=1;var t=4}else{var n=Q.$a(d.node,l);p=n.id;t=Q.Ab(n.mode)?2:Q.Sa(n.mode)?4:Q.mb(n.mode)?10:8}T=[p>>>0,(S=p,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];M[b+a>>2]=T[0];M[b+a+4>>2]=T[1];T=[280*(g+1)>>>0,(S=280*(g+1),1<=+Math.abs(S)?
0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];M[b+a+8>>2]=T[0];M[b+a+12>>2]=T[1];Ja[b+a+16>>1]=280;H[b+a+18>>0]=t;ya(l,G,b+a+19,256);a+=280;g+=1}Q.Wa(d,280*g,0);return a}catch(r){return"undefined"!==typeof Q&&r instanceof Q.Ka||C(r),-r.Oa}}function ac(a,b){if(w)return W(7,1,a,b);try{return bc(b,0,136),M[b>>2]=1,M[b+4>>2]=2,M[b+8>>2]=3,M[b+12>>2]=4,0}catch(c){return"undefined"!==typeof Q&&c instanceof Q.Ka||C(c),-c.Oa}}
function cc(a,b,c){if(w)return W(8,1,a,b,c);Tb=c;try{var d=Z(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=Ub();return M[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return f=Ub(),Q.ec(d,b,f);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:C("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof Q&&g instanceof Q.Ka||C(g),-g.Oa}}
function dc(a,b){if(w)return W(9,1,a,b);try{return a=I(a),Sb(Q.lstat,a,b)}catch(c){return"undefined"!==typeof Q&&c instanceof Q.Ka||C(c),-c.Oa}}function ec(a,b,c){if(w)return W(10,1,a,b,c);Tb=c;try{var d=I(a),f=c?Ub():0;return Q.open(d,b,f).fd}catch(g){return"undefined"!==typeof Q&&g instanceof Q.Ka||C(g),-g.Oa}}
function fc(a,b,c,d){if(w)return W(11,1,a,b,c,d);try{return d&&(M[d>>2]=-1,M[d+4>>2]=-1,M[d+8>>2]=-1,M[d+12>>2]=-1),0}catch(f){return"undefined"!==typeof Q&&f instanceof Q.Ka||C(f),-f.Oa}}function hc(a,b){if(w)return W(12,1,a,b);try{return a=I(a),b=I(b),Q.rename(a,b),0}catch(c){return"undefined"!==typeof Q&&c instanceof Q.Ka||C(c),-c.Oa}}function ic(a){if(w)return W(13,1,a);try{return a=I(a),Q.rmdir(a),0}catch(b){return"undefined"!==typeof Q&&b instanceof Q.Ka||C(b),-b.Oa}}
function jc(a,b){if(w)return W(14,1,a,b);try{return a=I(a),Sb(Q.stat,a,b)}catch(c){return"undefined"!==typeof Q&&c instanceof Q.Ka||C(c),-c.Oa}}function kc(a){if(w)return W(15,1,a);try{return a=I(a),Q.unlink(a),0}catch(b){return"undefined"!==typeof Q&&b instanceof Q.Ka||C(b),-b.Oa}}function lc(){void 0===lc.start&&(lc.start=Date.now());return 1E3*(Date.now()-lc.start)|0}var mc=[];
function nc(){u||q||(ra||(ra={}),ra["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(ra["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,h("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function oc(a,b,c){if(0>=a||a>H.length||a&1)return-28;if(ka){if(Atomics.load(M,a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(M,kb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(M,kb>>2,0),-73;d=Atomics.exchange(M,kb>>2,0);if(0==d)break;rb();if(Atomics.load(M,a>>2)!=b)return-6;Atomics.exchange(M,kb>>2,a)}return 0}a=Atomics.wait(M,a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function W(a,b){for(var c=arguments.length-2,d=za(),f=xa(8*c),g=f>>3,l=0;l<c;l++)La[g+l]=arguments[2+l];c=pc(a,c,f,b);Aa(d);return c}var qc=[],rc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function sc(a){a=2<a?I(a):a;return rc[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function tc(a,b,c){var d=sc(a);if(!d)return-4;d.Kb&&(M[d.Kb>>2]=b,M[d.Kb+4>>2]=c);if(d.Kc||!d.be)d.Kc&&(d=d.Kc),a=!1,d.Jb&&d.Jb.Ib&&(a=d.Jb.Ib.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Jb.Ib.viewport(0,0,b,c);else{if(d.Kb){d=M[d.Kb+8>>2];a=a?I(a):"";var f=za(),g=xa(12),l=0;if(a){l=Ea(a)+1;var p=L(l);ya(a,G,p,l);l=p}M[g>>2]=l;M[g+4>>2]=b;M[g+8>>2]=c;uc(0,d,657457152,0,l,g);Aa(f);return 1}return-4}return 0}
function vc(a,b,c){return w?W(16,1,a,b,c):tc(a,b,c)}function wc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,l){b.drawElementsInstancedANGLE(c,d,f,g,l)})}
function xc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function yc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function zc(a,b){a.Cc||(a.Cc=a.getContext,a.getContext=function(d,f){f=a.Cc(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?Ac(c,b):0}function Ac(a,b){var c=L(8);M[c+4>>2]=V();var d={ke:c,attributes:b,version:b.xd,Ib:a};a.canvas&&(a.canvas.Jb=d);("undefined"===typeof b.xc||b.xc)&&Bc(d);return c}
function Bc(a){a||(a=Cc);if(!a.rd){a.rd=!0;var b=a.Ib;wc(b);xc(b);yc(b);b.fe=b.getExtension("EXT_disjoint_timer_query");b.qe=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Cc,Dc=["default","low-power","high-performance"],Ec={};
function Fc(){if(!Gc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ia||"./this.program"},b;for(b in Ec)void 0===Ec[b]?delete a[b]:a[b]=Ec[b];var c=[];for(b in a)c.push(b+"="+a[b]);Gc=c}return Gc}var Gc;
function Hc(a,b){if(w)return W(17,1,a,b);try{var c=0;Fc().forEach(function(d,f){var g=b+c;M[a+4*f>>2]=g;Ha(d,g);c+=d.length+1});return 0}catch(d){return"undefined"!==typeof Q&&d instanceof Q.Ka||C(d),d.Oa}}function Ic(a,b){if(w)return W(18,1,a,b);try{var c=Fc();M[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});M[b>>2]=d;return 0}catch(f){return"undefined"!==typeof Q&&f instanceof Q.Ka||C(f),f.Oa}}
function Jc(a){if(w)return W(19,1,a);try{var b=Z(a);Q.close(b);return 0}catch(c){return"undefined"!==typeof Q&&c instanceof Q.Ka||C(c),c.Oa}}function Kc(a,b){if(w)return W(20,1,a,b);try{var c=Z(a);H[b>>0]=c.tty?2:Q.Sa(c.mode)?3:Q.mb(c.mode)?7:4;return 0}catch(d){return"undefined"!==typeof Q&&d instanceof Q.Ka||C(d),d.Oa}}
function Lc(a,b,c,d){if(w)return W(21,1,a,b,c,d);try{a:{for(var f=Z(a),g=a=0;g<c;g++){var l=M[b+(8*g+4)>>2],p=Q.read(f,H,M[b+8*g>>2],l,void 0);if(0>p){var t=-1;break a}a+=p;if(p<l)break}t=a}M[d>>2]=t;return 0}catch(n){return"undefined"!==typeof Q&&n instanceof Q.Ka||C(n),n.Oa}}
function Mc(a,b,c,d,f){if(w)return W(22,1,a,b,c,d,f);try{var g=Z(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Q.Wa(g,a,d);T=[g.position>>>0,(S=g.position,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];M[f>>2]=T[0];M[f+4>>2]=T[1];g.lb&&0===a&&0===d&&(g.lb=null);return 0}catch(l){return"undefined"!==typeof Q&&l instanceof Q.Ka||C(l),l.Oa}}
function Nc(a,b,c,d){if(w)return W(23,1,a,b,c,d);try{a:{for(var f=Z(a),g=a=0;g<c;g++){var l=Q.write(f,H,M[b+8*g>>2],M[b+(8*g+4)>>2],void 0);if(0>l){var p=-1;break a}a+=l}p=a}M[d>>2]=p;return 0}catch(t){return"undefined"!==typeof Q&&t instanceof Q.Ka||C(t),t.Oa}}
function sb(a){if(w)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=U.qd();if(!b)return 6;if(void 0!==b.Ya)throw"Internal error!";if(!a.Ob)throw"Internal error, no pthread ptr!";U.jb.push(b);for(var c=L(512),d=0;128>d;++d)M[c+4*d>>2]=0;var f=a.qb+a.ub;d=U.cb[a.Ob]={worker:b,qb:a.qb,ub:a.ub,Wb:a.Wb,eb:a.Ob};var g=d.eb>>2;Atomics.store(N,g+16,a.detached);Atomics.store(N,g+25,c);Atomics.store(N,g+10,d.eb);Atomics.store(N,g+20,a.ub);Atomics.store(N,g+19,
f);Atomics.store(N,g+26,a.ub);Atomics.store(N,g+28,f);Atomics.store(N,g+29,a.detached);c=Oc()+40;Atomics.store(N,g+43,c);b.Ya=d;var l={cmd:"run",start_routine:a.Md,arg:a.yb,threadInfoStruct:a.Ob,stackBase:a.qb,stackSize:a.ub};b.Gb=function(){l.time=performance.now();b.postMessage(l,a.Wd)};b.loaded&&(b.Gb(),delete b.Gb);return 0}
function Pc(a,b){if(!a)return h("pthread_join attempted on a null thread pointer!"),71;if(w&&V()==a)return h("PThread "+a+" is attempting to join to itself!"),16;if(!w&&Qc()==a)return h("Main thread "+a+" is attempting to join to itself!"),16;if(M[a+12>>2]!==a)return h("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(N,a+64>>2))return h("Attempted to join thread "+a+", which was already detached!"),28;for(nc();;){var c=
Atomics.load(N,a>>2);if(1==c)return c=Atomics.load(N,a+4>>2),b&&(M[b>>2]=c),Atomics.store(N,a+64>>2,1),w?postMessage({cmd:"cleanupThread",thread:a}):lb(a),0;if(w){var d=V();if(d&&!Atomics.load(N,d+56>>2)&&2==Atomics.load(N,d+0>>2))throw"Canceled!";}w||rb();oc(a,c,w?100:1)}}function Rc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Sc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Tc=[31,29,31,30,31,30,31,31,30,31,30,31],Uc=[31,28,31,30,31,30,31,31,30,31,30,31];
function Vc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Rc(a.getFullYear())?Tc:Uc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}function Wc(a,b,c,d){a||(a=this);this.parent=a;this.Ra=a.Ra;this.Db=null;this.id=Q.Bd++;this.name=b;this.mode=c;this.La={};this.Na={};this.rdev=d}
Object.defineProperties(Wc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},vd:{get:function(){return Q.Sa(this.mode)}},fc:{get:function(){return Q.Ab(this.mode)}}});Q.Qc=Wc;Q.Nd();var Rb,Xc=[null,zb,Vb,Wb,Xb,Zb,$b,ac,cc,dc,ec,fc,hc,ic,jc,kc,vc,Hc,Ic,Jc,Kc,Lc,Mc,Nc];
function Ob(a,b){var c=Array(Ea(a)+1);a=ya(a,c,0,c.length);b&&(c.length=a);return c}
var ad={c:function(a,b,c,d){C("Assertion failed: "+I(a)+", at: "+[b?I(b):"unknown filename",c,d?I(d):"unknown function"])},M:function(a,b){a=Yc(a,b);if(!vb())return postMessage({cmd:"exitProcess",returnCode:a}),a},fa:function(a,b){return xb(a,b)},G:function(a,b){return yb(a,b)},F:function(a,b){return Db(a,b)},V:Vb,Z:Wb,n:Xb,da:Zb,H:$b,K:ac,u:cc,ea:dc,w:ec,J:fc,aa:hc,_:ic,I:function(){return 0},ca:jc,$:kc,R:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(w)postMessage({targetThread:a,
cmd:"processThreadQueue"});else{a=(a=U.cb[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},b:function(){C()},S:lc,W:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=wb();else return M[Yb()>>2]=28,-1;M[b>>2]=a/1E3|0;M[b+4>>2]=a%1E3*1E6|0;return 0},s:function(a,b,c){mc.length=0;var d;for(c>>=2;d=G[b++];)(d=105>d)&&c&1&&c++,mc.push(d?La[c++>>1]:M[c]),++c;return gb[a].apply(null,mc)},L:nc,i:function(){},e:oc,f:ib,X:function(){return G.length},d:wb,B:function(a,
b,c){G.copyWithin(a,b,b+c)},Y:function(){return u?require("os").cpus().length:navigator.hardwareConcurrency},O:function(a,b,c){qc.length=b;c>>=3;for(var d=0;d<b;d++)qc[d]=La[c+d];return(0>a?gb[-a-1]:Xc[a]).apply(null,qc)},C:function(){C("OOM")},P:function(a,b,c){return sc(a)?tc(a,b,c):vc(a,b,c)},r:function(){},N:function(){},Q:function(a,b){b>>=2;b={alpha:!!M[b],depth:!!M[b+1],stencil:!!M[b+2],antialias:!!M[b+3],premultipliedAlpha:!!M[b+4],preserveDrawingBuffer:!!M[b+5],powerPreference:Dc[M[b+6]],
failIfMajorPerformanceCaveat:!!M[b+7],xd:M[b+8],oe:M[b+9],xc:M[b+10],md:M[b+11],te:M[b+12],ve:M[b+13]};a=sc(a);return!a||b.md?0:zc(a,b)},D:Hc,E:Ic,l:function(a){da(a)},j:Jc,t:Kc,v:Lc,z:Mc,m:Nc,ba:function(a){var b=Date.now();M[a>>2]=b/1E3|0;M[a+4>>2]=b%1E3*1E3|0;return 0},q:yb,A:function(){U.sd()},p:Db,a:E||e.wasmMemory,y:function(a){zb();var b=new Date(M[a+20>>2]+1900,M[a+16>>2],M[a+12>>2],M[a+8>>2],M[a+4>>2],M[a>>2],0),c=M[a+32>>2],d=b.getTimezoneOffset(),f=new Date(b.getFullYear(),0,1),g=(new Date(b.getFullYear(),
6,1)).getTimezoneOffset(),l=f.getTimezoneOffset(),p=Math.min(l,g);0>c?M[a+32>>2]=Number(g!=l&&p==d):0<c!=(p==d)&&(g=Math.max(l,g),b.setTime(b.getTime()+6E4*((0<c?p:g)-d)));M[a+24>>2]=b.getDay();M[a+28>>2]=(b.getTime()-f.getTime())/864E5|0;M[a>>2]=b.getSeconds();M[a+4>>2]=b.getMinutes();M[a+8>>2]=b.getHours();M[a+12>>2]=b.getDate();M[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},T:function(a){var b=U.Rb.pop();a&&b()},U:xb,g:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return h("Current environment does not support SharedArrayBuffer, pthreads are not available!"),
6;if(!a)return h("pthread_create called with a null thread pointer!"),28;var f=[];if(w&&0===f.length)return Zc(687865856,a,b,c,d);var g=0,l=0;if(b&&-1!=b){var p=M[b>>2];p+=81920;g=M[b+8>>2];l=0!==M[b+12>>2]}else p=2097152;(b=0==g)?g=$c(16,p):(g-=p,assert(0<g));for(var t=L(228),n=0;57>n;++n)N[(t>>2)+n]=0;M[a>>2]=t;M[t+12>>2]=t;a=t+152;M[a>>2]=a;c={qb:g,ub:p,Wb:b,detached:l,Md:c,Ob:t,yb:d,Wd:f};return w?(c.ae="spawnThread",postMessage(c,f),0):sb(c)},k:function(a,b){return Pc(a,b)},h:function(){return 0},
o:function(a,b,c,d){function f(m,v,y){for(m="number"===typeof m?m.toString():m||"";m.length<v;)m=y[0]+m;return m}function g(m,v){return f(m,v,"0")}function l(m,v){function y(O){return 0>O?-1:0<O?1:0}var J;0===(J=y(m.getFullYear()-v.getFullYear()))&&0===(J=y(m.getMonth()-v.getMonth()))&&(J=y(m.getDate()-v.getDate()));return J}function p(m){switch(m.getDay()){case 0:return new Date(m.getFullYear()-1,11,29);case 1:return m;case 2:return new Date(m.getFullYear(),0,3);case 3:return new Date(m.getFullYear(),
0,2);case 4:return new Date(m.getFullYear(),0,1);case 5:return new Date(m.getFullYear()-1,11,31);case 6:return new Date(m.getFullYear()-1,11,30)}}function t(m){m=Vc(new Date(m.Va+1900,0,1),m.Ub);var v=new Date(m.getFullYear()+1,0,4),y=p(new Date(m.getFullYear(),0,4));v=p(v);return 0>=l(y,m)?0>=l(v,m)?m.getFullYear()+1:m.getFullYear():m.getFullYear()-1}var n=M[d+40>>2];d={Ud:M[d>>2],Td:M[d+4>>2],Sb:M[d+8>>2],Hb:M[d+12>>2],vb:M[d+16>>2],Va:M[d+20>>2],Tb:M[d+24>>2],Ub:M[d+28>>2],ye:M[d+32>>2],Sd:M[d+
36>>2],Vd:n?I(n):""};c=I(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in n)c=c.replace(new RegExp(r,"g"),n[r]);var A="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
F="January February March April May June July August September October November December".split(" ");n={"%a":function(m){return A[m.Tb].substring(0,3)},"%A":function(m){return A[m.Tb]},"%b":function(m){return F[m.vb].substring(0,3)},"%B":function(m){return F[m.vb]},"%C":function(m){return g((m.Va+1900)/100|0,2)},"%d":function(m){return g(m.Hb,2)},"%e":function(m){return f(m.Hb,2," ")},"%g":function(m){return t(m).toString().substring(2)},"%G":function(m){return t(m)},"%H":function(m){return g(m.Sb,
2)},"%I":function(m){m=m.Sb;0==m?m=12:12<m&&(m-=12);return g(m,2)},"%j":function(m){return g(m.Hb+Sc(Rc(m.Va+1900)?Tc:Uc,m.vb-1),3)},"%m":function(m){return g(m.vb+1,2)},"%M":function(m){return g(m.Td,2)},"%n":function(){return"\n"},"%p":function(m){return 0<=m.Sb&&12>m.Sb?"AM":"PM"},"%S":function(m){return g(m.Ud,2)},"%t":function(){return"\t"},"%u":function(m){return m.Tb||7},"%U":function(m){var v=new Date(m.Va+1900,0,1),y=0===v.getDay()?v:Vc(v,7-v.getDay());m=new Date(m.Va+1900,m.vb,m.Hb);return 0>
l(y,m)?g(Math.ceil((31-y.getDate()+(Sc(Rc(m.getFullYear())?Tc:Uc,m.getMonth()-1)-31)+m.getDate())/7),2):0===l(y,v)?"01":"00"},"%V":function(m){var v=new Date(m.Va+1901,0,4),y=p(new Date(m.Va+1900,0,4));v=p(v);var J=Vc(new Date(m.Va+1900,0,1),m.Ub);return 0>l(J,y)?"53":0>=l(v,J)?"01":g(Math.ceil((y.getFullYear()<m.Va+1900?m.Ub+32-y.getDate():m.Ub+1-y.getDate())/7),2)},"%w":function(m){return m.Tb},"%W":function(m){var v=new Date(m.Va,0,1),y=1===v.getDay()?v:Vc(v,0===v.getDay()?1:7-v.getDay()+1);m=
new Date(m.Va+1900,m.vb,m.Hb);return 0>l(y,m)?g(Math.ceil((31-y.getDate()+(Sc(Rc(m.getFullYear())?Tc:Uc,m.getMonth()-1)-31)+m.getDate())/7),2):0===l(y,v)?"01":"00"},"%y":function(m){return(m.Va+1900).toString().substring(2)},"%Y":function(m){return m.Va+1900},"%z":function(m){m=m.Sd;var v=0<=m;m=Math.abs(m)/60;return(v?"+":"-")+String("0000"+(m/60*100+m%60)).slice(-4)},"%Z":function(m){return m.Vd},"%%":function(){return"%"}};for(r in n)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),n[r](d)));r=Ob(c,
!1);if(r.length>b)return 0;H.set(r,a);return r.length-1},x:function(a){var b=Date.now()/1E3|0;a&&(M[a>>2]=b);return b}};
(function(){function a(f,g){e.asm=f.exports;Na=e.asm.ia;Ra.unshift(e.asm.ga);U.oc.push(e.asm.na);ta=g;w||bb()}function b(f){a(f.instance,f.module)}function c(f){return eb().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){h("failed to asynchronously prepare wasm: "+g);C(g)})}var d={a:ad};w||ab();if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return h("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return sa||"function"!==typeof WebAssembly.instantiateStreaming||
cb()||R.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(R,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){h("wasm streaming compile failed: "+g);h("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.ga).apply(null,arguments)};
var pb=e._free=function(){return(pb=e._free=e.asm.ha).apply(null,arguments)},Yb=e.___errno_location=function(){return(Yb=e.___errno_location=e.asm.ja).apply(null,arguments)},L=e._malloc=function(){return(L=e._malloc=e.asm.ka).apply(null,arguments)};e._fflush=function(){return(e._fflush=e.asm.la).apply(null,arguments)};var Yc=e._main=function(){return(Yc=e._main=e.asm.ma).apply(null,arguments)};e._emscripten_tls_init=function(){return(e._emscripten_tls_init=e.asm.na).apply(null,arguments)};
e._emscripten_current_thread_process_queued_calls=function(){return(e._emscripten_current_thread_process_queued_calls=e.asm.oa).apply(null,arguments)};
var nb=e._emscripten_register_main_browser_thread_id=function(){return(nb=e._emscripten_register_main_browser_thread_id=e.asm.pa).apply(null,arguments)},Qc=e._emscripten_main_browser_thread_id=function(){return(Qc=e._emscripten_main_browser_thread_id=e.asm.qa).apply(null,arguments)},fb=e.__emscripten_do_dispatch_to_thread=function(){return(fb=e.__emscripten_do_dispatch_to_thread=e.asm.ra).apply(null,arguments)},Zc=e._emscripten_sync_run_in_main_thread_4=function(){return(Zc=e._emscripten_sync_run_in_main_thread_4=
e.asm.sa).apply(null,arguments)},rb=e._emscripten_main_thread_process_queued_calls=function(){return(rb=e._emscripten_main_thread_process_queued_calls=e.asm.ta).apply(null,arguments)},pc=e._emscripten_run_in_main_runtime_thread_js=function(){return(pc=e._emscripten_run_in_main_runtime_thread_js=e.asm.ua).apply(null,arguments)},uc=e.__emscripten_call_on_thread=function(){return(uc=e.__emscripten_call_on_thread=e.asm.va).apply(null,arguments)};
e._emscripten_proxy_main=function(){return(e._emscripten_proxy_main=e.asm.wa).apply(null,arguments)};
var mb=e.__emscripten_thread_init=function(){return(mb=e.__emscripten_thread_init=e.asm.xa).apply(null,arguments)},bc=e._memset=function(){return(bc=e._memset=e.asm.ya).apply(null,arguments)},V=e._pthread_self=function(){return(V=e._pthread_self=e.asm.za).apply(null,arguments)},ob=e.___pthread_tsd_run_dtors=function(){return(ob=e.___pthread_tsd_run_dtors=e.asm.Aa).apply(null,arguments)},Oc=e._emscripten_get_global_libc=function(){return(Oc=e._emscripten_get_global_libc=e.asm.Ba).apply(null,arguments)},
Cb=e.__get_tzname=function(){return(Cb=e.__get_tzname=e.asm.Ca).apply(null,arguments)},Bb=e.__get_daylight=function(){return(Bb=e.__get_daylight=e.asm.Da).apply(null,arguments)},Ab=e.__get_timezone=function(){return(Ab=e.__get_timezone=e.asm.Ea).apply(null,arguments)},za=e.stackSave=function(){return(za=e.stackSave=e.asm.Fa).apply(null,arguments)},Aa=e.stackRestore=function(){return(Aa=e.stackRestore=e.asm.Ga).apply(null,arguments)},xa=e.stackAlloc=function(){return(xa=e.stackAlloc=e.asm.Ha).apply(null,
arguments)},tb=e._emscripten_stack_set_limits=function(){return(tb=e._emscripten_stack_set_limits=e.asm.Ia).apply(null,arguments)},$c=e._memalign=function(){return($c=e._memalign=e.asm.Ja).apply(null,arguments)},qb=e.__emscripten_allow_main_runtime_queued_calls=1322616,kb=e.__emscripten_main_thread_futex=2920364;e.ccall=wa;e.cwrap=function(a,b,c,d){c=c||[];var f=c.every(function(g){return"number"===g});return"string"!==b&&f&&!d?va(a):function(){return wa(a,b,c,arguments,d)}};
e.setValue=function(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":H[a>>0]=b;break;case "i8":H[a>>0]=b;break;case "i16":Ja[a>>1]=b;break;case "i32":M[a>>2]=b;break;case "i64":T=[b>>>0,(S=b,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];M[a>>2]=T[0];M[a+4>>2]=T[1];break;case "float":Ka[a>>2]=b;break;case "double":La[a>>3]=b;break;default:C("invalid type for setValue: "+c)}};
e.writeAsciiToMemory=Ha;e.FS=Q;e.PThread=U;e.PThread=U;e.wasmMemory=E;e.ExitStatus=ca;var bd;function ca(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}$a=function cd(){bd||dd();bd||($a=cd)};
function dd(a){function b(){if(!bd&&(bd=!0,e.calledRun=!0,!ua)){Va();w||Wa(Sa);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(ed){var c=a,d=e._emscripten_proxy_main;c=c||[];var f=c.length+1,g=xa(4*(f+1));M[g>>2]=Ga(ia);for(var l=1;l<f;l++)M[(g>>2)+l]=Ga(c[l-1]);M[(g>>2)+f]=0;d(f,g)}if(!w){if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),Ua.unshift(c);Wa(Ua)}}}a=a||ha;if(!(0<Ya))if(w)aa(e),Va(),postMessage({cmd:"loaded"});else{if(!w){if(e.preRun)for("function"==
typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Xa();Wa(Qa)}0<Ya||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=dd;function da(a,b){if(!b||!vb()||0!==a){if(!b&&w)throw postMessage({cmd:"exitProcess",returnCode:a}),new ca(a);if(!vb()){U.Od();w||(Wa(Ta),Q.quit(),U.Mc());if(e.onExit)e.onExit(a);ua=!0}ja(a,new ca(a))}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();
var ed=!1;e.noInitialRun&&(ed=!1);w&&(noExitRuntime=!1,U.td());dd();


  return createFFmpegCore.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createFFmpegCore;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createFFmpegCore; });
else if (typeof exports === 'object')
  exports["createFFmpegCore"] = createFFmpegCore;
