
var createFFmpegCore = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createFFmpegCore) {
  createFFmpegCore = createFFmpegCore || {};


var e;e||(e=typeof createFFmpegCore !== 'undefined' ? createFFmpegCore : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});e.quit=function(a){if(e.onExit)e.onExit(a);throw new ca(a);};e.exit=da;ea=h=function(){};var fa={},k;for(k in e)e.hasOwnProperty(k)&&(fa[k]=e[k]);var ha=[],ia="./this.program";function ja(a,b){throw b;}var ka=!1,r=!1,v=!1,la=!1;ka="object"===typeof window;r="function"===typeof importScripts;v="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;
la=!ka&&!v&&!r;var w=e.ENVIRONMENT_IS_PTHREAD||!1,x="";function ma(a){return e.locateFile?e.locateFile(a,x):x+a}var z,na,oa,B,pa;
if(v){x=r?require("path").dirname(x)+"/":__dirname+"/";z=function(a,b){B||(B=require("fs"));pa||(pa=require("path"));a=pa.normalize(a);return B.readFileSync(a,b?null:"utf8")};oa=function(a){a=z(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ia=process.argv[1].replace(/\\/g,"/"));ha=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",C);ja=function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"};
var qa;try{qa=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=qa.Worker}else if(la)"undefined"!=typeof read&&(z=function(a){return read(a)}),oa=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ha=scriptArgs:"undefined"!=typeof arguments&&(ha=arguments),
"function"===typeof quit&&(ja=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ka||r)r?x=self.location.href:"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src),_scriptDir&&(x=_scriptDir),0!==x.indexOf("blob:")?x=x.substr(0,x.lastIndexOf("/")+1):x="",v?(z=function(a,b){B||(B=require("fs"));pa||(pa=require("path"));a=pa.normalize(a);
return B.readFileSync(a,b?null:"utf8")},oa=function(a){a=z(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(z=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},r&&(oa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),na=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&
d.response?b(d.response):c()};d.onerror=c;d.send(null)});v&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var ea=e.print||console.log.bind(console),h=e.printErr||console.warn.bind(console);for(k in fa)fa.hasOwnProperty(k)&&(e[k]=fa[k]);fa=null;e.arguments&&(ha=e.arguments);e.thisProgram&&(ia=e.thisProgram);e.quit&&(ja=e.quit);var ra,sa;e.wasmBinary&&(sa=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&C("no native wasm support detected");
var E,ta,ua=!1;function assert(a,b){a||C("Assertion failed: "+b)}function va(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function wa(a,b,c,d){var f={string:function(n){var q=0;if(null!==n&&void 0!==n&&0!==n){var A=(n.length<<2)+1;q=xa(A);ya(n,G,q,A)}return q},array:function(n){var q=xa(n.length);H.set(n,q);return q}},g=va(a),l=[];a=0;if(d)for(var p=0;p<d.length;p++){var t=f[c[p]];t?(0===a&&(a=za()),l[p]=t(d[p])):l[p]=d[p]}c=g.apply(null,l);c=function(n){return"string"===b?I(n):"boolean"===b?!!n:n}(c);0!==a&&Aa(a);return c}
function Ba(a){var b=new TextDecoder(a);this.decode=function(c){c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var Ca="undefined"!==typeof TextDecoder?new Ba("utf8"):void 0;
function Da(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ca)return Ca.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function I(a){return a?Da(G,a,void 0):""}
function ya(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var p=a.charCodeAt(++g);l=65536+((l&1023)<<10)|p&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-f}
function Ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new Ba("utf-16le");function Fa(a){var b=Ea(a)+1,c=L(b);c&&ya(a,H,c,b);return c}function Ga(a){var b=Ea(a)+1,c=xa(b);ya(a,H,c,b);return c}function Ha(a,b,c){for(var d=0;d<a.length;++d)H[b++>>0]=a.charCodeAt(d);c||(H[b>>0]=0)}var Ia,H,G,Ja,M,N,Ka,La;w&&(Ia=e.buffer);
var Ma=e.INITIAL_MEMORY||2146435072;
if(w)E=e.wasmMemory,Ia=e.buffer;else if(e.wasmMemory)E=e.wasmMemory;else if(E=new WebAssembly.Memory({initial:Ma/65536,maximum:Ma/65536,shared:!0}),!(E.buffer instanceof SharedArrayBuffer))throw h("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),v&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),Error("bad memory");
E&&(Ia=E.buffer);Ma=Ia.byteLength;var P=Ia;Ia=P;e.HEAP8=H=new Int8Array(P);e.HEAP16=Ja=new Int16Array(P);e.HEAP32=M=new Int32Array(P);e.HEAPU8=G=new Uint8Array(P);e.HEAPU16=new Uint16Array(P);e.HEAPU32=N=new Uint32Array(P);e.HEAPF32=Ka=new Float32Array(P);e.HEAPF64=La=new Float64Array(P);var Pa,Qa=[],Ra=[],Sa=[],Ta=[];function Ua(){w||(e.noFSInit||Q.yb.cc||Q.yb(),Q.Hc=!1,Va(Ra))}function Wa(){var a=e.preRun.shift();Qa.unshift(a)}var Xa=0,Ya=null,Za=null;
function $a(){assert(!w,"addRunDependency cannot be used in a pthread worker");Xa++;e.monitorRunDependencies&&e.monitorRunDependencies(Xa)}function ab(){Xa--;e.monitorRunDependencies&&e.monitorRunDependencies(Xa);if(0==Xa&&(null!==Ya&&(clearInterval(Ya),Ya=null),Za)){var a=Za;Za=null;a()}}e.preloadedImages={};e.preloadedAudios={};
function C(a){if(e.onAbort)e.onAbort(a);w&&console.error("Pthread aborting at "+Error().stack);h(a);ua=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function bb(){return R.startsWith("data:application/octet-stream;base64,")}var R;R="ffmpeg-core.wasm";bb()||(R=ma(R));function cb(){var a=R;try{if(a==R&&sa)return new Uint8Array(sa);if(oa)return oa(a);throw"both async and sync fetching of the wasm failed";}catch(b){C(b)}}
function db(){if(!sa&&(ka||r)){if("function"===typeof fetch&&!R.startsWith("file://"))return fetch(R,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+R+"'";return a.arrayBuffer()}).catch(function(){return cb()});if(na)return new Promise(function(a,b){na(R,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return cb()})}
var S,T,fb={1322624:function(){throw"Canceled!";},1322642:function(a,b){setTimeout(function(){eb(a,b)},0)}};function Va(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.he;"number"===typeof c?void 0===b.xb?Pa.get(c)():Pa.get(c)(b.xb):c(void 0===b.xb?null:b.xb)}}}
function gb(a,b){if(0>=a||a>H.length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(M,ib>>2),d=0;if(c==a&&Atomics.compareExchange(M,ib>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(M,a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}e._emscripten_futex_wake=gb;
function kb(a){if(w)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=U.bb[a];b&&(M[a+12>>2]=0,U.Ob(b.worker))}
var U={jb:[],ib:[],nc:[],ke:function(){},qd:function(){for(var a=L(228),b=0;57>b;++b)N[a/4+b]=0;M[a+12>>2]=a;b=a+152;M[b>>2]=b;var c=L(512);for(b=0;128>b;++b)N[c/4+b]=0;Atomics.store(N,a+100>>2,c);Atomics.store(N,a+40>>2,a);lb(a,!r,1);mb(a)},rd:function(){U.receiveObjectTransfer=U.Fd;U.threadInit=U.Qd;U.threadCancel=U.Od;U.threadExit=U.Pd;U.setExitStatus=U.Kd},bb:{},Qb:[],Hd:function(){for(;0<U.Qb.length;)U.Qb.pop()();w&&V()&&nb()},Lc:function(a,b){Atomics.store(N,a+56>>2,1);Atomics.store(N,a+60>>
2,0);U.Hd();Atomics.store(N,a+4>>2,b);Atomics.store(N,a+0>>2,1);gb(a+0,2147483647);lb(0,0,0)},Kd:function(){},Pd:function(a){var b=V();b&&(U.Lc(b,a),w&&postMessage({cmd:"exit"}))},Od:function(){U.Lc(V(),-1);postMessage({cmd:"cancelDone"})},Nd:function(){for(var a in U.bb){var b=U.bb[a];b&&b.worker&&U.Ob(b.worker)}U.bb={};for(a=0;a<U.jb.length;++a){var c=U.jb[a];c.terminate()}U.jb=[];for(a=0;a<U.ib.length;++a)c=U.ib[a],b=c.Xa,U.Zb(b),c.terminate();U.ib=[]},Zb:function(a){if(a){if(a.cb){var b=M[a.cb+
100>>2];M[a.cb+100>>2]=0;ob(b);ob(a.cb)}a.cb=0;a.Vb&&a.pb&&ob(a.pb);a.pb=0;a.worker&&(a.worker.Xa=null)}},Ob:function(a){U.Id(function(){delete U.bb[a.Xa.cb];U.jb.push(a);U.ib.splice(U.ib.indexOf(a),1);U.Zb(a.Xa);a.Xa=void 0})},Id:function(a){M[pb>>2]=0;try{a()}finally{M[pb>>2]=1}},Fd:function(){},Qd:function(){for(var a in U.nc)U.nc[a]()},ud:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.Xa&&(U.hd=a.Xa.cb);if(d.targetThread&&d.targetThread!=V()){var g=U.bb[d.we];g?g.worker.postMessage(c.data,
d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===f)qb();else if("spawnThread"===f)rb(c.data);else if("cleanupThread"===f)kb(d.thread);else if("killThread"===f){c=d.thread;if(w)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";M[c+12>>2]=0;c=U.bb[c];c.worker.terminate();
U.Zb(c);U.ib.splice(U.ib.indexOf(c.worker),1);c.worker.Xa=void 0}else if("cancelThread"===f){c=d.thread;if(w)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";U.bb[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===f)a.loaded=!0,b&&b(a),a.Fb&&(a.Fb(),delete a.Fb);else if("print"===f)ea("Thread "+d.threadId+": "+d.text);else if("printErr"===f)h("Thread "+d.threadId+": "+d.text);else if("alert"===
f)alert("Thread "+d.threadId+": "+d.text);else if("exit"===f)a.Xa&&Atomics.load(N,a.Xa.cb+64>>2)&&U.Ob(a);else if("exitProcess"===f)try{da(d.returnCode)}catch(l){if(l instanceof ca)return;throw l;}else"cancelDone"===f?U.Ob(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):h("worker sent an unknown command "+f));U.hd=void 0};a.onerror=function(c){h("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};v&&(a.on("message",function(c){a.onmessage({data:c})}),
a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));a.postMessage({cmd:"load",urlOrBlob:e.mainScriptUrlOrBlob||_scriptDir,wasmMemory:E,wasmModule:ta})},Vc:function(){var a=ma("ffmpeg-core.worker.js");U.jb.push(new Worker(a))},od:function(){0==U.jb.length&&(U.Vc(),U.ud(U.jb[0]));return U.jb.pop()},Zd:function(a){for(a=performance.now()+a;performance.now()<a;);}};e.establishStackSpace=function(a,b){sb(a,b);Aa(a)};e.invokeEntryPoint=function(a,b){return Pa.get(a)(b)};var tb=0;
function ub(){return noExitRuntime||0<tb}e.keepRuntimeAlive=ub;var vb;v?vb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:w?vb=function(){return performance.now()-e.__performance_now_clock_drift}:"undefined"!==typeof dateNow?vb=dateNow:vb=function(){return performance.now()};function wb(a,b){U.Qb.push(function(){Pa.get(a)(b)})}
function xb(a,b){a=new Date(1E3*M[a>>2]);M[b>>2]=a.getUTCSeconds();M[b+4>>2]=a.getUTCMinutes();M[b+8>>2]=a.getUTCHours();M[b+12>>2]=a.getUTCDate();M[b+16>>2]=a.getUTCMonth();M[b+20>>2]=a.getUTCFullYear()-1900;M[b+24>>2]=a.getUTCDay();M[b+36>>2]=0;M[b+32>>2]=0;M[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;xb.qc||(xb.qc=Fa("GMT"));M[b+40>>2]=xb.qc;return b}
function yb(){function a(l){return(l=l.toTimeString().match(/\(([A-Za-z ]+)\)$/))?l[1]:"GMT"}if(w)return W(1,1);if(!yb.Xc){yb.Xc=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var f=d.getTimezoneOffset(),g=Math.max(b,f);M[zb()>>2]=60*g;M[Ab()>>2]=Number(b!=f);c=a(c);d=a(d);c=Fa(c);d=Fa(d);f<b?(M[Bb()>>2]=c,M[Bb()+4>>2]=d):(M[Bb()>>2]=d,M[Bb()+4>>2]=c)}}
function Cb(a,b){yb();a=new Date(1E3*M[a>>2]);M[b>>2]=a.getSeconds();M[b+4>>2]=a.getMinutes();M[b+8>>2]=a.getHours();M[b+12>>2]=a.getDate();M[b+16>>2]=a.getMonth();M[b+20>>2]=a.getFullYear()-1900;M[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);M[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;M[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;M[b+32>>2]=a;a=M[Bb()+(a?4:0)>>2];
M[b+40>>2]=a;return b}function Db(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Eb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Db(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Fb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function X(a){if("/"===a)return"/";a=Eb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Gb(a,b){return Eb(a+"/"+b)}
function Hb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(v)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){C("randomDevice")}}
function Ib(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:Q.cwd();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Db(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}
function Jb(a,b){function c(l){for(var p=0;p<l.length&&""===l[p];p++);for(var t=l.length-1;0<=t&&""===l[t];t--);return p>t?[]:l.slice(p,t-p+1)}a=Ib(a).substr(1);b=Ib(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")}var Kb=[];function Lb(a,b){Kb[a]={input:[],output:[],sb:b};Q.mc(a,Mb)}
var Mb={open:function(a){var b=Kb[a.node.rdev];if(!b)throw new Q.Ja(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.sb.flush(a.tty)},flush:function(a){a.tty.sb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.sb.Dc)throw new Q.Ja(60);for(var f=0,g=0;g<d;g++){try{var l=a.tty.sb.Dc(a.tty)}catch(p){throw new Q.Ja(29);}if(void 0===l&&0===f)throw new Q.Ja(6);if(null===l||void 0===l)break;f++;b[c+g]=l}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.sb.jc)throw new Q.Ja(60);
try{for(var f=0;f<d;f++)a.tty.sb.jc(a.tty,b[c+f])}catch(g){throw new Q.Ja(29);}d&&(a.node.timestamp=Date.now());return f}},Ob={Dc:function(a){if(!a.input.length){var b=null;if(v){var c=Buffer.qb?Buffer.qb(256):new Buffer(256),d=0;try{d=B.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(f.toString().includes("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Nb(b,!0)}return a.input.shift()},jc:function(a,b){null===b||10===b?(ea(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ea(Da(a.output,0)),a.output=[])}},Pb={jc:function(a,b){null===b||10===b?(h(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(Da(a.output,0)),a.output=[])}},Y={ab:null,Qa:function(){return Y.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(Q.sd(c)||Q.isFIFO(c))throw new Q.Ja(63);Y.ab||(Y.ab={dir:{node:{Ya:Y.Ka.Ya,Ta:Y.Ka.Ta,lookup:Y.Ka.lookup,eb:Y.Ka.eb,rename:Y.Ka.rename,unlink:Y.Ka.unlink,rmdir:Y.Ka.rmdir,readdir:Y.Ka.readdir,symlink:Y.Ka.symlink},stream:{Va:Y.Ma.Va}},file:{node:{Ya:Y.Ka.Ya,Ta:Y.Ka.Ta},stream:{Va:Y.Ma.Va,read:Y.Ma.read,write:Y.Ma.write,wb:Y.Ma.wb,Bb:Y.Ma.Bb,Eb:Y.Ma.Eb}},link:{node:{Ya:Y.Ka.Ya,Ta:Y.Ka.Ta,readlink:Y.Ka.readlink},stream:{}},sc:{node:{Ya:Y.Ka.Ya,Ta:Y.Ka.Ta},
stream:Q.Zc}});c=Q.createNode(a,b,c,d);Q.Ra(c.mode)?(c.Ka=Y.ab.dir.node,c.Ma=Y.ab.dir.stream,c.La={}):Q.isFile(c.mode)?(c.Ka=Y.ab.file.node,c.Ma=Y.ab.file.stream,c.Pa=0,c.La=null):Q.lb(c.mode)?(c.Ka=Y.ab.link.node,c.Ma=Y.ab.link.stream):Q.zb(c.mode)&&(c.Ka=Y.ab.sc.node,c.Ma=Y.ab.sc.stream);c.timestamp=Date.now();a&&(a.La[b]=c,a.timestamp=c.timestamp);return c},ie:function(a){return a.La?a.La.subarray?a.La.subarray(0,a.Pa):new Uint8Array(a.La):new Uint8Array(0)},yc:function(a,b){var c=a.La?a.La.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.La,a.La=new Uint8Array(b),0<a.Pa&&a.La.set(c.subarray(0,a.Pa),0))},Gd:function(a,b){if(a.Pa!=b)if(0==b)a.La=null,a.Pa=0;else{var c=a.La;a.La=new Uint8Array(b);c&&a.La.set(c.subarray(0,Math.min(b,a.Pa)));a.Pa=b}},Ka:{Ya:function(a){var b={};b.dev=Q.zb(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;Q.Ra(a.mode)?b.size=4096:Q.isFile(a.mode)?b.size=a.Pa:Q.lb(a.mode)?b.size=a.link.length:b.size=
0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Wc=4096;b.blocks=Math.ceil(b.size/b.Wc);return b},Ta:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&Y.Gd(a,b.size)},lookup:function(){throw Q.$b[44];},eb:function(a,b,c,d){return Y.createNode(a,b,c,d)},rename:function(a,b,c){if(Q.Ra(a.mode)){try{var d=Q.Za(b,c)}catch(g){}if(d)for(var f in d.La)throw new Q.Ja(55);}delete a.parent.La[a.name];
a.parent.timestamp=Date.now();a.name=c;b.La[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.La[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=Q.Za(a,b),d;for(d in c.La)throw new Q.Ja(55);delete a.La[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.La)a.La.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=Y.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!Q.lb(a.mode))throw new Q.Ja(28);return a.link}},
Ma:{read:function(a,b,c,d,f){var g=a.node.La;if(f>=a.node.Pa)return 0;a=Math.min(a.node.Pa-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.La||a.La.subarray)){if(g)return a.La=b.subarray(c,c+d),a.Pa=d;if(0===a.Pa&&0===f)return a.La=b.slice(c,c+d),a.Pa=d;if(f+d<=a.Pa)return a.La.set(b.subarray(c,c+d),f),d}Y.yc(a,f+d);if(a.La.subarray&&b.subarray)a.La.set(b.subarray(c,
c+d),f);else for(g=0;g<d;g++)a.La[f+g]=b[c+g];a.Pa=Math.max(a.Pa,f+d);return d},Va:function(a,b,c){1===c?b+=a.position:2===c&&Q.isFile(a.node.mode)&&(b+=a.node.Pa);if(0>b)throw new Q.Ja(28);return b},wb:function(a,b,c){Y.yc(a.node,b+c);a.node.Pa=Math.max(a.node.Pa,b+c)},Bb:function(a,b,c,d,f,g){if(0!==b)throw new Q.Ja(28);if(!Q.isFile(a.node.mode))throw new Q.Ja(43);a=a.node.La;if(g&2||a.buffer!==Ia){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=
65536*Math.ceil(c/65536);for(b=L(g);c<g;)H[b+c++]=0;c=b;if(!c)throw new Q.Ja(48);H.set(a,c)}else d=!1,c=a.byteOffset;return{te:c,Xd:d}},Eb:function(a,b,c,d,f){if(!Q.isFile(a.node.mode))throw new Q.Ja(43);if(f&2)return 0;Y.Ma.write(a,b,0,d,c,!1);return 0}}},Q={root:null,Db:[],vc:{},streams:[],zd:1,$a:null,uc:"/",cc:!1,Hc:!0,Sa:{},Nc:{Kc:{Rc:1,Sc:2}},Ja:null,$b:{},ld:null,Pb:0,Oa:function(a,b){a=Ib(Q.cwd(),a);b=b||{};if(!a)return{path:"",node:null};var c={Yb:!0,lc:0},d;for(d in c)void 0===b[d]&&(b[d]=
c[d]);if(8<b.lc)throw new Q.Ja(32);a=Db(a.split("/").filter(function(l){return!!l}),!1);var f=Q.root;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=Q.Za(f,a[d]);c=Gb(c,a[d]);Q.mb(f)&&(!g||g&&b.Yb)&&(f=f.Cb.root);if(!g||b.Wa)for(g=0;Q.lb(f.mode);)if(f=Q.readlink(c),c=Ib(Fb(c),f),f=Q.Oa(c,{lc:b.lc}).node,40<g++)throw new Q.Ja(32);}return{path:c,node:f}},gb:function(a){for(var b;;){if(Q.Kb(a))return a=a.Qa.Ic,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},
bc:function(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Q.$a.length},Fc:function(a){var b=Q.bc(a.parent.id,a.name);a.ob=Q.$a[b];Q.$a[b]=a},Gc:function(a){var b=Q.bc(a.parent.id,a.name);if(Q.$a[b]===a)Q.$a[b]=a.ob;else for(b=Q.$a[b];b;){if(b.ob===a){b.ob=a.ob;break}b=b.ob}},Za:function(a,b){var c=Q.wd(a);if(c)throw new Q.Ja(c,a);for(c=Q.$a[Q.bc(a.id,b)];c;c=c.ob){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return Q.lookup(a,b)},createNode:function(a,b,c,
d){a=new Q.Oc(a,b,c,d);Q.Fc(a);return a},Xb:function(a){Q.Gc(a)},Kb:function(a){return a===a.parent},mb:function(a){return!!a.Cb},isFile:function(a){return 32768===(a&61440)},Ra:function(a){return 16384===(a&61440)},lb:function(a){return 40960===(a&61440)},zb:function(a){return 8192===(a&61440)},sd:function(a){return 24576===(a&61440)},isFIFO:function(a){return 4096===(a&61440)},isSocket:function(a){return 49152===(a&49152)},md:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},yd:function(a){var b=Q.md[a];
if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},zc:function(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},hb:function(a,b){if(Q.Hc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},wd:function(a){var b=Q.hb(a,"x");return b?b:a.Ka.lookup?0:2},ic:function(a,b){try{return Q.Za(a,b),20}catch(c){}return Q.hb(a,"wx")},Lb:function(a,b,c){try{var d=Q.Za(a,b)}catch(f){return f.Na}if(a=
Q.hb(a,"wx"))return a;if(c){if(!Q.Ra(d.mode))return 54;if(Q.Kb(d)||Q.gb(d)===Q.cwd())return 10}else if(Q.Ra(d.mode))return 31;return 0},xd:function(a,b){return a?Q.lb(a.mode)?32:Q.Ra(a.mode)&&("r"!==Q.zc(b)||b&512)?31:Q.hb(a,Q.zc(b)):44},Qc:4096,Ad:function(a,b){b=b||Q.Qc;for(a=a||0;a<=b;a++)if(!Q.streams[a])return a;throw new Q.Ja(33);},rb:function(a){return Q.streams[a]},gd:function(a,b,c){Q.Ub||(Q.Ub=function(){},Q.Ub.prototype={object:{get:function(){return this.node},set:function(g){this.node=
g}}});var d=new Q.Ub,f;for(f in a)d[f]=a[f];a=d;b=Q.Ad(b,c);a.fd=b;return Q.streams[b]=a},$c:function(a){Q.streams[a]=null},Zc:{open:function(a){a.Ma=Q.nd(a.node.rdev).Ma;a.Ma.open&&a.Ma.open(a)},Va:function(){throw new Q.Ja(70);}},hc:function(a){return a>>8},me:function(a){return a&255},nb:function(a,b){return a<<8|b},mc:function(a,b){Q.vc[a]={Ma:b}},nd:function(a){return Q.vc[a]},Cc:function(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.Db)}return b},Mc:function(a,b){function c(l){Q.Pb--;
return b(l)}function d(l){if(l){if(!d.jd)return d.jd=!0,c(l)}else++g>=f.length&&c(null)}"function"===typeof a&&(b=a,a=!1);Q.Pb++;1<Q.Pb&&h("warning: "+Q.Pb+" FS.syncfs operations in flight at once, probably just doing extra work");var f=Q.Cc(Q.root.Qa),g=0;f.forEach(function(l){if(!l.type.Mc)return d(null);l.type.Mc(l,a,d)})},Qa:function(a,b,c){var d="/"===c,f=!c;if(d&&Q.root)throw new Q.Ja(10);if(!d&&!f){var g=Q.Oa(c,{Yb:!1});c=g.path;g=g.node;if(Q.mb(g))throw new Q.Ja(10);if(!Q.Ra(g.mode))throw new Q.Ja(54);
}b={type:a,re:b,Ic:c,Db:[]};a=a.Qa(b);a.Qa=b;b.root=a;d?Q.root=a:g&&(g.Cb=b,g.Qa&&g.Qa.Db.push(b));return a},ye:function(a){a=Q.Oa(a,{Yb:!1});if(!Q.mb(a.node))throw new Q.Ja(28);a=a.node;var b=a.Cb,c=Q.Cc(b);Object.keys(Q.$a).forEach(function(d){for(d=Q.$a[d];d;){var f=d.ob;c.includes(d.Qa)&&Q.Xb(d);d=f}});a.Cb=null;a.Qa.Db.splice(a.Qa.Db.indexOf(b),1)},lookup:function(a,b){return a.Ka.lookup(a,b)},eb:function(a,b,c){var d=Q.Oa(a,{parent:!0}).node;a=X(a);if(!a||"."===a||".."===a)throw new Q.Ja(28);
var f=Q.ic(d,a);if(f)throw new Q.Ja(f);if(!d.Ka.eb)throw new Q.Ja(63);return d.Ka.eb(d,a,b,c)},create:function(a,b){return Q.eb(a,(void 0!==b?b:438)&4095|32768,0)},mkdir:function(a,b){return Q.eb(a,(void 0!==b?b:511)&1023|16384,0)},oe:function(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{Q.mkdir(c,b)}catch(f){if(20!=f.Na)throw f;}}},Mb:function(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Q.eb(a,b|8192,c)},symlink:function(a,b){if(!Ib(a))throw new Q.Ja(44);var c=
Q.Oa(b,{parent:!0}).node;if(!c)throw new Q.Ja(44);b=X(b);var d=Q.ic(c,b);if(d)throw new Q.Ja(d);if(!c.Ka.symlink)throw new Q.Ja(63);return c.Ka.symlink(c,b,a)},rename:function(a,b){var c=Fb(a),d=Fb(b),f=X(a),g=X(b);var l=Q.Oa(a,{parent:!0});var p=l.node;l=Q.Oa(b,{parent:!0});l=l.node;if(!p||!l)throw new Q.Ja(44);if(p.Qa!==l.Qa)throw new Q.Ja(75);var t=Q.Za(p,f);d=Jb(a,d);if("."!==d.charAt(0))throw new Q.Ja(28);d=Jb(b,c);if("."!==d.charAt(0))throw new Q.Ja(55);try{var n=Q.Za(l,g)}catch(q){}if(t!==
n){c=Q.Ra(t.mode);if(f=Q.Lb(p,f,c))throw new Q.Ja(f);if(f=n?Q.Lb(l,g,c):Q.ic(l,g))throw new Q.Ja(f);if(!p.Ka.rename)throw new Q.Ja(63);if(Q.mb(t)||n&&Q.mb(n))throw new Q.Ja(10);if(l!==p&&(f=Q.hb(p,"w")))throw new Q.Ja(f);try{Q.Sa.willMovePath&&Q.Sa.willMovePath(a,b)}catch(q){h("FS.trackingDelegate['willMovePath']('"+a+"', '"+b+"') threw an exception: "+q.message)}Q.Gc(t);try{p.Ka.rename(t,l,g)}catch(q){throw q;}finally{Q.Fc(t)}try{if(Q.Sa.onMovePath)Q.Sa.onMovePath(a,b)}catch(q){h("FS.trackingDelegate['onMovePath']('"+
a+"', '"+b+"') threw an exception: "+q.message)}}},rmdir:function(a){var b=Q.Oa(a,{parent:!0}).node,c=X(a),d=Q.Za(b,c),f=Q.Lb(b,c,!0);if(f)throw new Q.Ja(f);if(!b.Ka.rmdir)throw new Q.Ja(63);if(Q.mb(d))throw new Q.Ja(10);try{Q.Sa.willDeletePath&&Q.Sa.willDeletePath(a)}catch(g){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.Ka.rmdir(b,c);Q.Xb(d);try{if(Q.Sa.onDeletePath)Q.Sa.onDeletePath(a)}catch(g){h("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+
g.message)}},readdir:function(a){a=Q.Oa(a,{Wa:!0}).node;if(!a.Ka.readdir)throw new Q.Ja(54);return a.Ka.readdir(a)},unlink:function(a){var b=Q.Oa(a,{parent:!0}).node,c=X(a),d=Q.Za(b,c),f=Q.Lb(b,c,!1);if(f)throw new Q.Ja(f);if(!b.Ka.unlink)throw new Q.Ja(63);if(Q.mb(d))throw new Q.Ja(10);try{Q.Sa.willDeletePath&&Q.Sa.willDeletePath(a)}catch(g){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.Ka.unlink(b,c);Q.Xb(d);try{if(Q.Sa.onDeletePath)Q.Sa.onDeletePath(a)}catch(g){h("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+g.message)}},readlink:function(a){a=Q.Oa(a).node;if(!a)throw new Q.Ja(44);if(!a.Ka.readlink)throw new Q.Ja(28);return Ib(Q.gb(a.parent),a.Ka.readlink(a))},stat:function(a,b){a=Q.Oa(a,{Wa:!b}).node;if(!a)throw new Q.Ja(44);if(!a.Ka.Ya)throw new Q.Ja(63);return a.Ka.Ya(a)},lstat:function(a){return Q.stat(a,!0)},chmod:function(a,b,c){a="string"===typeof a?Q.Oa(a,{Wa:!c}).node:a;if(!a.Ka.Ta)throw new Q.Ja(63);a.Ka.Ta(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:function(a,
b){Q.chmod(a,b,!0)},fchmod:function(a,b){a=Q.rb(a);if(!a)throw new Q.Ja(8);Q.chmod(a.node,b)},chown:function(a,b,c,d){a="string"===typeof a?Q.Oa(a,{Wa:!d}).node:a;if(!a.Ka.Ta)throw new Q.Ja(63);a.Ka.Ta(a,{timestamp:Date.now()})},lchown:function(a,b,c){Q.chown(a,b,c,!0)},fchown:function(a,b,c){a=Q.rb(a);if(!a)throw new Q.Ja(8);Q.chown(a.node,b,c)},truncate:function(a,b){if(0>b)throw new Q.Ja(28);a="string"===typeof a?Q.Oa(a,{Wa:!0}).node:a;if(!a.Ka.Ta)throw new Q.Ja(63);if(Q.Ra(a.mode))throw new Q.Ja(31);
if(!Q.isFile(a.mode))throw new Q.Ja(28);var c=Q.hb(a,"w");if(c)throw new Q.Ja(c);a.Ka.Ta(a,{size:b,timestamp:Date.now()})},ge:function(a,b){a=Q.rb(a);if(!a)throw new Q.Ja(8);if(0===(a.flags&2097155))throw new Q.Ja(28);Q.truncate(a.node,b)},ze:function(a,b,c){a=Q.Oa(a,{Wa:!0}).node;a.Ka.Ta(a,{timestamp:Math.max(b,c)})},open:function(a,b,c,d,f){if(""===a)throw new Q.Ja(44);b="string"===typeof b?Q.yd(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Eb(a);
try{g=Q.Oa(a,{Wa:!(b&131072)}).node}catch(p){}}var l=!1;if(b&64)if(g){if(b&128)throw new Q.Ja(20);}else g=Q.eb(a,c,0),l=!0;if(!g)throw new Q.Ja(44);Q.zb(g.mode)&&(b&=-513);if(b&65536&&!Q.Ra(g.mode))throw new Q.Ja(54);if(!l&&(c=Q.xd(g,b)))throw new Q.Ja(c);b&512&&Q.truncate(g,0);b&=-131713;d=Q.gd({node:g,path:Q.gb(g),flags:b,seekable:!0,position:0,Ma:g.Ma,Wd:[],error:!1},d,f);d.Ma.open&&d.Ma.open(d);!e.logReadFiles||b&1||(Q.kc||(Q.kc={}),a in Q.kc||(Q.kc[a]=1,h("FS.trackingDelegate error on read file: "+
a)));try{Q.Sa.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=Q.Nc.Kc.Rc),0!==(b&2097155)&&(f|=Q.Nc.Kc.Sc),Q.Sa.onOpenFile(a,f))}catch(p){h("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+p.message)}return d},close:function(a){if(Q.Ab(a))throw new Q.Ja(8);a.kb&&(a.kb=null);try{a.Ma.close&&a.Ma.close(a)}catch(b){throw b;}finally{Q.$c(a.fd)}a.fd=null},Ab:function(a){return null===a.fd},Va:function(a,b,c){if(Q.Ab(a))throw new Q.Ja(8);if(!a.seekable||!a.Ma.Va)throw new Q.Ja(70);if(0!=c&&
1!=c&&2!=c)throw new Q.Ja(28);a.position=a.Ma.Va(a,b,c);a.Wd=[];return a.position},read:function(a,b,c,d,f){if(0>d||0>f)throw new Q.Ja(28);if(Q.Ab(a))throw new Q.Ja(8);if(1===(a.flags&2097155))throw new Q.Ja(8);if(Q.Ra(a.node.mode))throw new Q.Ja(31);if(!a.Ma.read)throw new Q.Ja(28);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new Q.Ja(70);b=a.Ma.read(a,b,c,d,f);g||(a.position+=b);return b},write:function(a,b,c,d,f,g){if(0>d||0>f)throw new Q.Ja(28);if(Q.Ab(a))throw new Q.Ja(8);
if(0===(a.flags&2097155))throw new Q.Ja(8);if(Q.Ra(a.node.mode))throw new Q.Ja(31);if(!a.Ma.write)throw new Q.Ja(28);a.seekable&&a.flags&1024&&Q.Va(a,0,2);var l="undefined"!==typeof f;if(!l)f=a.position;else if(!a.seekable)throw new Q.Ja(70);b=a.Ma.write(a,b,c,d,f,g);l||(a.position+=b);try{if(a.path&&Q.Sa.onWriteToFile)Q.Sa.onWriteToFile(a.path)}catch(p){h("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+p.message)}return b},wb:function(a,b,c){if(Q.Ab(a))throw new Q.Ja(8);
if(0>b||0>=c)throw new Q.Ja(28);if(0===(a.flags&2097155))throw new Q.Ja(8);if(!Q.isFile(a.node.mode)&&!Q.Ra(a.node.mode))throw new Q.Ja(43);if(!a.Ma.wb)throw new Q.Ja(138);a.Ma.wb(a,b,c)},Bb:function(a,b,c,d,f,g){if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new Q.Ja(2);if(1===(a.flags&2097155))throw new Q.Ja(2);if(!a.Ma.Bb)throw new Q.Ja(43);return a.Ma.Bb(a,b,c,d,f,g)},Eb:function(a,b,c,d,f){return a&&a.Ma.Eb?a.Ma.Eb(a,b,c,d,f):0},qe:function(){return 0},dc:function(a,b,c){if(!a.Ma.dc)throw new Q.Ja(59);
return a.Ma.dc(a,b,c)},readFile:function(a,b){b=b||{};b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,d=Q.open(a,b.flags);a=Q.stat(a).size;var f=new Uint8Array(a);Q.read(d,f,0,a,0);"utf8"===b.encoding?c=Da(f,0):"binary"===b.encoding&&(c=f);Q.close(d);return c},writeFile:function(a,b,c){c=c||{};c.flags=c.flags||577;a=Q.open(a,c.flags,c.mode);if("string"===typeof b){var d=new Uint8Array(Ea(b)+
1);b=ya(b,d,0,d.length);Q.write(a,d,0,b,void 0,c.Yc)}else if(ArrayBuffer.isView(b))Q.write(a,b,0,b.byteLength,void 0,c.Yc);else throw Error("Unsupported data type");Q.close(a)},cwd:function(){return Q.uc},chdir:function(a){a=Q.Oa(a,{Wa:!0});if(null===a.node)throw new Q.Ja(44);if(!Q.Ra(a.node.mode))throw new Q.Ja(54);var b=Q.hb(a.node,"x");if(b)throw new Q.Ja(b);Q.uc=a.path},bd:function(){Q.mkdir("/tmp");Q.mkdir("/home");Q.mkdir("/home/web_user")},ad:function(){Q.mkdir("/dev");Q.mc(Q.nb(1,3),{read:function(){return 0},
write:function(b,c,d,f){return f}});Q.Mb("/dev/null",Q.nb(1,3));Lb(Q.nb(5,0),Ob);Lb(Q.nb(6,0),Pb);Q.Mb("/dev/tty",Q.nb(5,0));Q.Mb("/dev/tty1",Q.nb(6,0));var a=Hb();Q.fb("/dev","random",a);Q.fb("/dev","urandom",a);Q.mkdir("/dev/shm");Q.mkdir("/dev/shm/tmp")},dd:function(){Q.mkdir("/proc");var a=Q.mkdir("/proc/self");Q.mkdir("/proc/self/fd");Q.Qa({Qa:function(){var b=Q.createNode(a,"fd",16895,73);b.Ka={lookup:function(c,d){var f=Q.rb(+d);if(!f)throw new Q.Ja(8);c={parent:null,Qa:{Ic:"fake"},Ka:{readlink:function(){return f.path}}};
return c.parent=c}};return b}},{},"/proc/self/fd")},ed:function(){e.stdin?Q.fb("/dev","stdin",e.stdin):Q.symlink("/dev/tty","/dev/stdin");e.stdout?Q.fb("/dev","stdout",null,e.stdout):Q.symlink("/dev/tty","/dev/stdout");e.stderr?Q.fb("/dev","stderr",null,e.stderr):Q.symlink("/dev/tty1","/dev/stderr");Q.open("/dev/stdin",0);Q.open("/dev/stdout",1);Q.open("/dev/stderr",1)},xc:function(){Q.Ja||(Q.Ja=function(a,b){this.node=b;this.Jd=function(c){this.Na=c};this.Jd(a);this.message="FS error"},Q.Ja.prototype=
Error(),Q.Ja.prototype.constructor=Q.Ja,[44].forEach(function(a){Q.$b[a]=new Q.Ja(a);Q.$b[a].stack="<generic error, no stack>"}))},Md:function(){Q.xc();Q.$a=Array(4096);Q.Qa(Y,{},"/");Q.bd();Q.ad();Q.dd();Q.ld={MEMFS:Y}},yb:function(a,b,c){Q.yb.cc=!0;Q.xc();e.stdin=a||e.stdin;e.stdout=b||e.stdout;e.stderr=c||e.stderr;Q.ed()},quit:function(){Q.yb.cc=!1;var a=e._fflush;a&&a(0);for(a=0;a<Q.streams.length;a++){var b=Q.streams[a];b&&Q.close(b)}},ac:function(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c},
fe:function(a,b){a=Q.Wb(a,b);return a.exists?a.object:null},Wb:function(a,b){try{var c=Q.Oa(a,{Wa:!b});a=c.path}catch(f){}var d={Kb:!1,exists:!1,error:0,name:null,path:null,object:null,Bd:!1,Dd:null,Cd:null};try{c=Q.Oa(a,{parent:!0}),d.Bd=!0,d.Dd=c.path,d.Cd=c.node,d.name=X(a),c=Q.Oa(a,{Wa:!b}),d.exists=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.Kb="/"===c.path}catch(f){d.error=f.Na}return d},ce:function(a,b){a="string"===typeof a?a:Q.gb(a);for(b=b.split("/").reverse();b.length;){var c=
b.pop();if(c){var d=Gb(a,c);try{Q.mkdir(d)}catch(f){}a=d}}return d},cd:function(a,b,c,d,f){a=Gb("string"===typeof a?a:Q.gb(a),b);return Q.create(a,Q.ac(d,f))},tc:function(a,b,c,d,f,g){a=b?Gb("string"===typeof a?a:Q.gb(a),b):a;d=Q.ac(d,f);f=Q.create(a,d);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var l=c.length;b<l;++b)a[b]=c.charCodeAt(b);c=a}Q.chmod(f,d|146);a=Q.open(f,577);Q.write(a,c,0,c.length,0,g);Q.close(a);Q.chmod(f,d)}return f},fb:function(a,b,c,d){a=Gb("string"===typeof a?a:
Q.gb(a),b);b=Q.ac(!!c,!!d);Q.fb.hc||(Q.fb.hc=64);var f=Q.nb(Q.fb.hc++,0);Q.mc(f,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,l,p,t){for(var n=0,q=0;q<t;q++){try{var A=c()}catch(F){throw new Q.Ja(29);}if(void 0===A&&0===n)throw new Q.Ja(6);if(null===A||void 0===A)break;n++;l[p+q]=A}n&&(g.node.timestamp=Date.now());return n},write:function(g,l,p,t){for(var n=0;n<t;n++)try{d(l[p+n])}catch(q){throw new Q.Ja(29);}t&&(g.node.timestamp=Date.now());
return n}});return Q.Mb(a,b,f)},Ac:function(a){if(a.ec||a.td||a.link||a.La)return!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(z)try{a.La=Nb(z(a.url),!0),a.Pa=a.La.length}catch(b){throw new Q.Ja(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},be:function(a,b,c,d,f){function g(){this.fc=
!1;this.qb=[]}g.prototype.get=function(n){if(!(n>this.length-1||0>n)){var q=n%this.chunkSize;return this.Ec(n/this.chunkSize|0)[q]}};g.prototype.Pc=function(n){this.Ec=n};g.prototype.rc=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var q=Number(n.getResponseHeader("Content-length")),A,F=(A=n.getResponseHeader("Accept-Ranges"))&&"bytes"===A;n=(A=n.getResponseHeader("Content-Encoding"))&&
"gzip"===A;var m=1048576;F||(m=q);var u=this;u.Pc(function(y){var J=y*m,O=(y+1)*m-1;O=Math.min(O,q-1);if("undefined"===typeof u.qb[y]){var hb=u.qb;if(J>O)throw Error("invalid range ("+J+", "+O+") or no bytes requested!");if(O>q-1)throw Error("only "+q+" bytes available! programmer error!");var D=new XMLHttpRequest;D.open("GET",c,!1);q!==m&&D.setRequestHeader("Range","bytes="+J+"-"+O);"undefined"!=typeof Uint8Array&&(D.responseType="arraybuffer");D.overrideMimeType&&D.overrideMimeType("text/plain; charset=x-user-defined");
D.send(null);if(!(200<=D.status&&300>D.status||304===D.status))throw Error("Couldn't load "+c+". Status: "+D.status);J=void 0!==D.response?new Uint8Array(D.response||[]):Nb(D.responseText||"",!0);hb[y]=J}if("undefined"===typeof u.qb[y])throw Error("doXHR failed!");return u.qb[y]});if(n||!q)m=q=1,m=q=this.Ec(0).length,ea("LazyFiles on gzip forces download of the whole file when length is accessed");this.Uc=q;this.Tc=m;this.fc=!0};if("undefined"!==typeof XMLHttpRequest){if(!r)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var l=new g;Object.defineProperties(l,{length:{get:function(){this.fc||this.rc();return this.Uc}},chunkSize:{get:function(){this.fc||this.rc();return this.Tc}}});l={ec:!1,La:l}}else l={ec:!1,url:c};var p=Q.cd(a,b,l,d,f);l.La?p.La=l.La:l.url&&(p.La=null,p.url=l.url);Object.defineProperties(p,{Pa:{get:function(){return this.La.length}}});var t={};Object.keys(p.Ma).forEach(function(n){var q=p.Ma[n];t[n]=function(){Q.Ac(p);return q.apply(null,arguments)}});t.read=function(n,q,A,F,m){Q.Ac(p);n=n.node.La;
if(m>=n.length)return 0;F=Math.min(n.length-m,F);if(n.slice)for(var u=0;u<F;u++)q[A+u]=n[m+u];else for(u=0;u<F;u++)q[A+u]=n.get(m+u);return F};p.Ma=t;return p},de:function(a,b,c,d,f,g,l,p,t,n){function q(F){function m(y){n&&n();p||Q.tc(a,b,y,d,f,t);g&&g();ab()}var u=!1;e.preloadPlugins.forEach(function(y){!u&&y.canHandle(A)&&(y.handle(F,A,m,function(){l&&l();ab()}),u=!0)});u||m(F)}Qb.yb();var A=b?Ib(Gb(a,b)):a;$a();"string"==typeof c?Qb.Yd(c,function(F){q(F)},l):q(c)},indexedDB:function(){return window.indexedDB||
window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},oc:function(){return"EM_FS_"+window.location.pathname},pc:20,vb:"FILE_DATA",ve:function(a,b,c){b=b||function(){};c=c||function(){};var d=Q.indexedDB();try{var f=d.open(Q.oc(),Q.pc)}catch(g){return c(g)}f.onupgradeneeded=function(){ea("creating db");f.result.createObjectStore(Q.vb)};f.onsuccess=function(){var g=f.result.transaction([Q.vb],"readwrite"),l=g.objectStore(Q.vb),p=0,t=0,n=a.length;a.forEach(function(q){q=l.put(Q.Wb(q).object.La,
q);q.onsuccess=function(){p++;p+t==n&&(0==t?b():c())};q.onerror=function(){t++;p+t==n&&(0==t?b():c())}});g.onerror=c};f.onerror=c},le:function(a,b,c){b=b||function(){};c=c||function(){};var d=Q.indexedDB();try{var f=d.open(Q.oc(),Q.pc)}catch(g){return c(g)}f.onupgradeneeded=c;f.onsuccess=function(){var g=f.result;try{var l=g.transaction([Q.vb],"readonly")}catch(A){c(A);return}var p=l.objectStore(Q.vb),t=0,n=0,q=a.length;a.forEach(function(A){var F=p.get(A);F.onsuccess=function(){Q.Wb(A).exists&&Q.unlink(A);
Q.tc(Fb(A),X(A),F.result,!0,!0,!0);t++;t+n==q&&(0==n?b():c())};F.onerror=function(){n++;t+n==q&&(0==n?b():c())}});l.onerror=c};f.onerror=c}};
function Rb(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&Eb(b)!==Eb(Q.gb(f.node)))return-54;throw f;}M[c>>2]=d.dev;M[c+4>>2]=0;M[c+8>>2]=d.ino;M[c+12>>2]=d.mode;M[c+16>>2]=d.nlink;M[c+20>>2]=d.uid;M[c+24>>2]=d.gid;M[c+28>>2]=d.rdev;M[c+32>>2]=0;T=[d.size>>>0,(S=d.size,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];M[c+40>>2]=T[0];M[c+44>>2]=T[1];M[c+48>>2]=4096;M[c+52>>2]=d.blocks;M[c+56>>2]=d.atime.getTime()/1E3|0;M[c+60>>
2]=0;M[c+64>>2]=d.mtime.getTime()/1E3|0;M[c+68>>2]=0;M[c+72>>2]=d.ctime.getTime()/1E3|0;M[c+76>>2]=0;T=[d.ino>>>0,(S=d.ino,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];M[c+80>>2]=T[0];M[c+84>>2]=T[1];return 0}var Sb=void 0;function Tb(){Sb+=4;return M[Sb-4>>2]}function Z(a){a=Q.rb(a);if(!a)throw new Q.Ja(8);return a}
function Ub(a,b,c,d,f){if(w)return W(2,1,a,b,c,d,f);try{f=0;for(var g=b?M[b>>2]:0,l=b?M[b+4>>2]:0,p=c?M[c>>2]:0,t=c?M[c+4>>2]:0,n=d?M[d>>2]:0,q=d?M[d+4>>2]:0,A=0,F=0,m=0,u=0,y=0,J=0,O=(b?M[b>>2]:0)|(c?M[c>>2]:0)|(d?M[d>>2]:0),hb=(b?M[b+4>>2]:0)|(c?M[c+4>>2]:0)|(d?M[d+4>>2]:0),D=0;D<a;D++){var K=1<<D%32;if(32>D?O&K:hb&K){var Na=Q.rb(D);if(!Na)throw new Q.Ja(8);var Oa=5;Na.Ma.Ed&&(Oa=Na.Ma.Ed(Na));Oa&1&&(32>D?g&K:l&K)&&(32>D?A|=K:F|=K,f++);Oa&4&&(32>D?p&K:t&K)&&(32>D?m|=K:u|=K,f++);Oa&2&&(32>D?n&K:
q&K)&&(32>D?y|=K:J|=K,f++)}}b&&(M[b>>2]=A,M[b+4>>2]=F);c&&(M[c>>2]=m,M[c+4>>2]=u);d&&(M[d>>2]=y,M[d+4>>2]=J);return f}catch(jb){return"undefined"!==typeof Q&&jb instanceof Q.Ja||C(jb),-jb.Na}}function Vb(a,b){if(w)return W(3,1,a,b);try{a=I(a);if(b&-8)var c=-28;else{var d;(d=Q.Oa(a,{Wa:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&Q.hb(d,a)?-2:0):c=-44}return c}catch(f){return"undefined"!==typeof Q&&f instanceof Q.Ja||C(f),-f.Na}}
function Wb(a,b,c){if(w)return W(4,1,a,b,c);Sb=c;try{var d=Z(a);switch(b){case 0:var f=Tb();return 0>f?-28:Q.open(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=Tb(),d.flags|=f,0;case 12:return f=Tb(),Ja[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return M[Xb()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof Q&&g instanceof Q.Ja||C(g),-g.Na}}
function Yb(a,b){if(w)return W(5,1,a,b);try{var c=Z(a);return Rb(Q.stat,c.path,b)}catch(d){return"undefined"!==typeof Q&&d instanceof Q.Ja||C(d),-d.Na}}
function Zb(a,b,c){if(w)return W(6,1,a,b,c);try{var d=Z(a);d.kb||(d.kb=Q.readdir(d.path));a=0;for(var f=Q.Va(d,0,1),g=Math.floor(f/280);g<d.kb.length&&a+280<=c;){var l=d.kb[g];if("."===l[0]){var p=1;var t=4}else{var n=Q.Za(d.node,l);p=n.id;t=Q.zb(n.mode)?2:Q.Ra(n.mode)?4:Q.lb(n.mode)?10:8}T=[p>>>0,(S=p,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];M[b+a>>2]=T[0];M[b+a+4>>2]=T[1];T=[280*(g+1)>>>0,(S=280*(g+1),1<=+Math.abs(S)?
0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];M[b+a+8>>2]=T[0];M[b+a+12>>2]=T[1];Ja[b+a+16>>1]=280;H[b+a+18>>0]=t;ya(l,G,b+a+19,256);a+=280;g+=1}Q.Va(d,280*g,0);return a}catch(q){return"undefined"!==typeof Q&&q instanceof Q.Ja||C(q),-q.Na}}function $b(a,b){if(w)return W(7,1,a,b);try{return ac(b,0,136),M[b>>2]=1,M[b+4>>2]=2,M[b+8>>2]=3,M[b+12>>2]=4,0}catch(c){return"undefined"!==typeof Q&&c instanceof Q.Ja||C(c),-c.Na}}
function bc(a,b,c){if(w)return W(8,1,a,b,c);Sb=c;try{var d=Z(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=Tb();return M[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return f=Tb(),Q.dc(d,b,f);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:C("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof Q&&g instanceof Q.Ja||C(g),-g.Na}}
function cc(a,b){if(w)return W(9,1,a,b);try{return a=I(a),Rb(Q.lstat,a,b)}catch(c){return"undefined"!==typeof Q&&c instanceof Q.Ja||C(c),-c.Na}}function dc(a,b,c){if(w)return W(10,1,a,b,c);Sb=c;try{var d=I(a),f=c?Tb():0;return Q.open(d,b,f).fd}catch(g){return"undefined"!==typeof Q&&g instanceof Q.Ja||C(g),-g.Na}}
function ec(a,b,c,d){if(w)return W(11,1,a,b,c,d);try{return d&&(M[d>>2]=-1,M[d+4>>2]=-1,M[d+8>>2]=-1,M[d+12>>2]=-1),0}catch(f){return"undefined"!==typeof Q&&f instanceof Q.Ja||C(f),-f.Na}}function fc(a,b){if(w)return W(12,1,a,b);try{return a=I(a),b=I(b),Q.rename(a,b),0}catch(c){return"undefined"!==typeof Q&&c instanceof Q.Ja||C(c),-c.Na}}function hc(a){if(w)return W(13,1,a);try{return a=I(a),Q.rmdir(a),0}catch(b){return"undefined"!==typeof Q&&b instanceof Q.Ja||C(b),-b.Na}}
function ic(a,b){if(w)return W(14,1,a,b);try{return a=I(a),Rb(Q.stat,a,b)}catch(c){return"undefined"!==typeof Q&&c instanceof Q.Ja||C(c),-c.Na}}function jc(a){if(w)return W(15,1,a);try{return a=I(a),Q.unlink(a),0}catch(b){return"undefined"!==typeof Q&&b instanceof Q.Ja||C(b),-b.Na}}function kc(){void 0===kc.start&&(kc.start=Date.now());return 1E3*(Date.now()-kc.start)|0}var lc=[];
function mc(){v||r||(ra||(ra={}),ra["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(ra["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,h("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function nc(a,b,c){if(0>=a||a>H.length||a&1)return-28;if(ka){if(Atomics.load(M,a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(M,ib>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(M,ib>>2,0),-73;d=Atomics.exchange(M,ib>>2,0);if(0==d)break;qb();if(Atomics.load(M,a>>2)!=b)return-6;Atomics.exchange(M,ib>>2,a)}return 0}a=Atomics.wait(M,a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function W(a,b){for(var c=arguments.length-2,d=za(),f=xa(8*c),g=f>>3,l=0;l<c;l++)La[g+l]=arguments[2+l];c=oc(a,c,f,b);Aa(d);return c}var pc=[],qc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function rc(a){a=2<a?I(a):a;return qc[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function sc(a,b,c){var d=rc(a);if(!d)return-4;d.Jb&&(M[d.Jb>>2]=b,M[d.Jb+4>>2]=c);if(d.Jc||!d.ae)d.Jc&&(d=d.Jc),a=!1,d.Ib&&d.Ib.Hb&&(a=d.Ib.Hb.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Ib.Hb.viewport(0,0,b,c);else{if(d.Jb){d=M[d.Jb+8>>2];a=a?I(a):"";var f=za(),g=xa(12),l=0;if(a){l=Ea(a)+1;var p=L(l);ya(a,G,p,l);l=p}M[g>>2]=l;M[g+4>>2]=b;M[g+8>>2]=c;tc(0,d,657457152,0,l,g);Aa(f);return 1}return-4}return 0}
function uc(a,b,c){return w?W(16,1,a,b,c):sc(a,b,c)}function vc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,l){b.drawElementsInstancedANGLE(c,d,f,g,l)})}
function wc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function xc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function yc(a,b){a.Bc||(a.Bc=a.getContext,a.getContext=function(d,f){f=a.Bc(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?zc(c,b):0}function zc(a,b){var c=L(8);M[c+4>>2]=V();var d={je:c,attributes:b,version:b.vd,Hb:a};a.canvas&&(a.canvas.Ib=d);("undefined"===typeof b.wc||b.wc)&&Ac(d);return c}
function Ac(a){a||(a=Bc);if(!a.pd){a.pd=!0;var b=a.Hb;vc(b);wc(b);xc(b);b.ee=b.getExtension("EXT_disjoint_timer_query");b.pe=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Bc,Cc=["default","low-power","high-performance"],Dc={};
function Ec(){if(!Fc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ia||"./this.program"},b;for(b in Dc)void 0===Dc[b]?delete a[b]:a[b]=Dc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Fc=c}return Fc}var Fc;
function Gc(a,b){if(w)return W(17,1,a,b);try{var c=0;Ec().forEach(function(d,f){var g=b+c;M[a+4*f>>2]=g;Ha(d,g);c+=d.length+1});return 0}catch(d){return"undefined"!==typeof Q&&d instanceof Q.Ja||C(d),d.Na}}function Hc(a,b){if(w)return W(18,1,a,b);try{var c=Ec();M[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});M[b>>2]=d;return 0}catch(f){return"undefined"!==typeof Q&&f instanceof Q.Ja||C(f),f.Na}}
function Ic(a){if(w)return W(19,1,a);try{var b=Z(a);Q.close(b);return 0}catch(c){return"undefined"!==typeof Q&&c instanceof Q.Ja||C(c),c.Na}}function Jc(a,b){if(w)return W(20,1,a,b);try{var c=Z(a);H[b>>0]=c.tty?2:Q.Ra(c.mode)?3:Q.lb(c.mode)?7:4;return 0}catch(d){return"undefined"!==typeof Q&&d instanceof Q.Ja||C(d),d.Na}}
function Kc(a,b,c,d){if(w)return W(21,1,a,b,c,d);try{a:{for(var f=Z(a),g=a=0;g<c;g++){var l=M[b+(8*g+4)>>2],p=Q.read(f,H,M[b+8*g>>2],l,void 0);if(0>p){var t=-1;break a}a+=p;if(p<l)break}t=a}M[d>>2]=t;return 0}catch(n){return"undefined"!==typeof Q&&n instanceof Q.Ja||C(n),n.Na}}
function Lc(a,b,c,d,f){if(w)return W(22,1,a,b,c,d,f);try{var g=Z(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Q.Va(g,a,d);T=[g.position>>>0,(S=g.position,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];M[f>>2]=T[0];M[f+4>>2]=T[1];g.kb&&0===a&&0===d&&(g.kb=null);return 0}catch(l){return"undefined"!==typeof Q&&l instanceof Q.Ja||C(l),l.Na}}
function Mc(a,b,c,d){if(w)return W(23,1,a,b,c,d);try{a:{for(var f=Z(a),g=a=0;g<c;g++){var l=Q.write(f,H,M[b+8*g>>2],M[b+(8*g+4)>>2],void 0);if(0>l){var p=-1;break a}a+=l}p=a}M[d>>2]=p;return 0}catch(t){return"undefined"!==typeof Q&&t instanceof Q.Ja||C(t),t.Na}}
function rb(a){if(w)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=U.od();if(!b)return 6;if(void 0!==b.Xa)throw"Internal error!";if(!a.Nb)throw"Internal error, no pthread ptr!";U.ib.push(b);for(var c=L(512),d=0;128>d;++d)M[c+4*d>>2]=0;var f=a.pb+a.tb;d=U.bb[a.Nb]={worker:b,pb:a.pb,tb:a.tb,Vb:a.Vb,cb:a.Nb};var g=d.cb>>2;Atomics.store(N,g+16,a.detached);Atomics.store(N,g+25,c);Atomics.store(N,g+10,d.cb);Atomics.store(N,g+20,a.tb);Atomics.store(N,g+19,
f);Atomics.store(N,g+26,a.tb);Atomics.store(N,g+28,f);Atomics.store(N,g+29,a.detached);c=Nc()+40;Atomics.store(N,g+43,c);b.Xa=d;var l={cmd:"run",start_routine:a.Ld,arg:a.xb,threadInfoStruct:a.Nb,stackBase:a.pb,stackSize:a.tb};b.Fb=function(){l.time=performance.now();b.postMessage(l,a.Vd)};b.loaded&&(b.Fb(),delete b.Fb);return 0}
function Oc(a,b){if(!a)return h("pthread_join attempted on a null thread pointer!"),71;if(w&&V()==a)return h("PThread "+a+" is attempting to join to itself!"),16;if(!w&&Pc()==a)return h("Main thread "+a+" is attempting to join to itself!"),16;if(M[a+12>>2]!==a)return h("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(N,a+64>>2))return h("Attempted to join thread "+a+", which was already detached!"),28;for(mc();;){var c=
Atomics.load(N,a>>2);if(1==c)return c=Atomics.load(N,a+4>>2),b&&(M[b>>2]=c),Atomics.store(N,a+64>>2,1),w?postMessage({cmd:"cleanupThread",thread:a}):kb(a),0;if(w){var d=V();if(d&&!Atomics.load(N,d+56>>2)&&2==Atomics.load(N,d+0>>2))throw"Canceled!";}w||qb();nc(a,c,w?100:1)}}function Qc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Rc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Sc=[31,29,31,30,31,30,31,31,30,31,30,31],Tc=[31,28,31,30,31,30,31,31,30,31,30,31];
function Uc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Qc(a.getFullYear())?Sc:Tc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}function Vc(a,b,c,d){a||(a=this);this.parent=a;this.Qa=a.Qa;this.Cb=null;this.id=Q.zd++;this.name=b;this.mode=c;this.Ka={};this.Ma={};this.rdev=d}
Object.defineProperties(Vc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},td:{get:function(){return Q.Ra(this.mode)}},ec:{get:function(){return Q.zb(this.mode)}}});Q.Oc=Vc;Q.Md();var Qb,Wc=[null,yb,Ub,Vb,Wb,Yb,Zb,$b,bc,cc,dc,ec,fc,hc,ic,jc,uc,Gc,Hc,Ic,Jc,Kc,Lc,Mc];
function Nb(a,b){var c=Array(Ea(a)+1);a=ya(a,c,0,c.length);b&&(c.length=a);return c}
var $c={c:function(a,b,c,d){C("Assertion failed: "+I(a)+", at: "+[b?I(b):"unknown filename",c,d?I(d):"unknown function"])},M:function(a,b){Xc(a,b)},fa:function(a,b){return wb(a,b)},G:function(a,b){return xb(a,b)},F:function(a,b){return Cb(a,b)},V:Ub,Z:Vb,n:Wb,da:Yb,H:Zb,K:$b,u:bc,ea:cc,w:dc,J:ec,aa:fc,_:hc,I:function(){return 0},ca:ic,$:jc,R:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(w)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=U.bb[a])&&a.worker;
if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},b:function(){C()},S:kc,W:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=vb();else return M[Xb()>>2]=28,-1;M[b>>2]=a/1E3|0;M[b+4>>2]=a%1E3*1E6|0;return 0},s:function(a,b,c){lc.length=0;var d;for(c>>=2;d=G[b++];)(d=105>d)&&c&1&&c++,lc.push(d?La[c++>>1]:M[c]),++c;return fb[a].apply(null,lc)},L:mc,i:function(){},e:nc,f:gb,X:function(){return G.length},d:vb,B:function(a,b,c){G.copyWithin(a,b,b+c)},Y:function(){return v?require("os").cpus().length:
navigator.hardwareConcurrency},O:function(a,b,c){pc.length=b;c>>=3;for(var d=0;d<b;d++)pc[d]=La[c+d];return(0>a?fb[-a-1]:Wc[a]).apply(null,pc)},C:function(){C("OOM")},P:function(a,b,c){return rc(a)?sc(a,b,c):uc(a,b,c)},r:function(){},N:function(){},Q:function(a,b){b>>=2;b={alpha:!!M[b],depth:!!M[b+1],stencil:!!M[b+2],antialias:!!M[b+3],premultipliedAlpha:!!M[b+4],preserveDrawingBuffer:!!M[b+5],powerPreference:Cc[M[b+6]],failIfMajorPerformanceCaveat:!!M[b+7],vd:M[b+8],ne:M[b+9],wc:M[b+10],kd:M[b+11],
se:M[b+12],ue:M[b+13]};a=rc(a);return!a||b.kd?0:yc(a,b)},D:Gc,E:Hc,l:function(a){da(a)},j:Ic,t:Jc,v:Kc,z:Lc,m:Mc,ba:function(a){var b=Date.now();M[a>>2]=b/1E3|0;M[a+4>>2]=b%1E3*1E3|0;return 0},q:xb,A:function(){U.qd()},p:Cb,a:E||e.wasmMemory,y:function(a){yb();var b=new Date(M[a+20>>2]+1900,M[a+16>>2],M[a+12>>2],M[a+8>>2],M[a+4>>2],M[a>>2],0),c=M[a+32>>2],d=b.getTimezoneOffset(),f=new Date(b.getFullYear(),0,1),g=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),l=f.getTimezoneOffset(),p=Math.min(l,
g);0>c?M[a+32>>2]=Number(g!=l&&p==d):0<c!=(p==d)&&(g=Math.max(l,g),b.setTime(b.getTime()+6E4*((0<c?p:g)-d)));M[a+24>>2]=b.getDay();M[a+28>>2]=(b.getTime()-f.getTime())/864E5|0;M[a>>2]=b.getSeconds();M[a+4>>2]=b.getMinutes();M[a+8>>2]=b.getHours();M[a+12>>2]=b.getDate();M[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},T:function(a){var b=U.Qb.pop();a&&b()},U:wb,g:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return h("Current environment does not support SharedArrayBuffer, pthreads are not available!"),
6;if(!a)return h("pthread_create called with a null thread pointer!"),28;var f=[];if(w&&0===f.length)return Yc(687865856,a,b,c,d);var g=0,l=0;if(b&&-1!=b){var p=M[b>>2];p+=81920;g=M[b+8>>2];l=0!==M[b+12>>2]}else p=2097152;(b=0==g)?g=Zc(16,p):(g-=p,assert(0<g));for(var t=L(228),n=0;57>n;++n)N[(t>>2)+n]=0;M[a>>2]=t;M[t+12>>2]=t;a=t+152;M[a>>2]=a;c={pb:g,tb:p,Vb:b,detached:l,Ld:c,Nb:t,xb:d,Vd:f};return w?(c.$d="spawnThread",postMessage(c,f),0):rb(c)},k:function(a,b){return Oc(a,b)},h:function(){return 0},
o:function(a,b,c,d){function f(m,u,y){for(m="number"===typeof m?m.toString():m||"";m.length<u;)m=y[0]+m;return m}function g(m,u){return f(m,u,"0")}function l(m,u){function y(O){return 0>O?-1:0<O?1:0}var J;0===(J=y(m.getFullYear()-u.getFullYear()))&&0===(J=y(m.getMonth()-u.getMonth()))&&(J=y(m.getDate()-u.getDate()));return J}function p(m){switch(m.getDay()){case 0:return new Date(m.getFullYear()-1,11,29);case 1:return m;case 2:return new Date(m.getFullYear(),0,3);case 3:return new Date(m.getFullYear(),
0,2);case 4:return new Date(m.getFullYear(),0,1);case 5:return new Date(m.getFullYear()-1,11,31);case 6:return new Date(m.getFullYear()-1,11,30)}}function t(m){m=Uc(new Date(m.Ua+1900,0,1),m.Tb);var u=new Date(m.getFullYear()+1,0,4),y=p(new Date(m.getFullYear(),0,4));u=p(u);return 0>=l(y,m)?0>=l(u,m)?m.getFullYear()+1:m.getFullYear():m.getFullYear()-1}var n=M[d+40>>2];d={Td:M[d>>2],Sd:M[d+4>>2],Rb:M[d+8>>2],Gb:M[d+12>>2],ub:M[d+16>>2],Ua:M[d+20>>2],Sb:M[d+24>>2],Tb:M[d+28>>2],xe:M[d+32>>2],Rd:M[d+
36>>2],Ud:n?I(n):""};c=I(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var A="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
F="January February March April May June July August September October November December".split(" ");n={"%a":function(m){return A[m.Sb].substring(0,3)},"%A":function(m){return A[m.Sb]},"%b":function(m){return F[m.ub].substring(0,3)},"%B":function(m){return F[m.ub]},"%C":function(m){return g((m.Ua+1900)/100|0,2)},"%d":function(m){return g(m.Gb,2)},"%e":function(m){return f(m.Gb,2," ")},"%g":function(m){return t(m).toString().substring(2)},"%G":function(m){return t(m)},"%H":function(m){return g(m.Rb,
2)},"%I":function(m){m=m.Rb;0==m?m=12:12<m&&(m-=12);return g(m,2)},"%j":function(m){return g(m.Gb+Rc(Qc(m.Ua+1900)?Sc:Tc,m.ub-1),3)},"%m":function(m){return g(m.ub+1,2)},"%M":function(m){return g(m.Sd,2)},"%n":function(){return"\n"},"%p":function(m){return 0<=m.Rb&&12>m.Rb?"AM":"PM"},"%S":function(m){return g(m.Td,2)},"%t":function(){return"\t"},"%u":function(m){return m.Sb||7},"%U":function(m){var u=new Date(m.Ua+1900,0,1),y=0===u.getDay()?u:Uc(u,7-u.getDay());m=new Date(m.Ua+1900,m.ub,m.Gb);return 0>
l(y,m)?g(Math.ceil((31-y.getDate()+(Rc(Qc(m.getFullYear())?Sc:Tc,m.getMonth()-1)-31)+m.getDate())/7),2):0===l(y,u)?"01":"00"},"%V":function(m){var u=new Date(m.Ua+1901,0,4),y=p(new Date(m.Ua+1900,0,4));u=p(u);var J=Uc(new Date(m.Ua+1900,0,1),m.Tb);return 0>l(J,y)?"53":0>=l(u,J)?"01":g(Math.ceil((y.getFullYear()<m.Ua+1900?m.Tb+32-y.getDate():m.Tb+1-y.getDate())/7),2)},"%w":function(m){return m.Sb},"%W":function(m){var u=new Date(m.Ua,0,1),y=1===u.getDay()?u:Uc(u,0===u.getDay()?1:7-u.getDay()+1);m=
new Date(m.Ua+1900,m.ub,m.Gb);return 0>l(y,m)?g(Math.ceil((31-y.getDate()+(Rc(Qc(m.getFullYear())?Sc:Tc,m.getMonth()-1)-31)+m.getDate())/7),2):0===l(y,u)?"01":"00"},"%y":function(m){return(m.Ua+1900).toString().substring(2)},"%Y":function(m){return m.Ua+1900},"%z":function(m){m=m.Rd;var u=0<=m;m=Math.abs(m)/60;return(u?"+":"-")+String("0000"+(m/60*100+m%60)).slice(-4)},"%Z":function(m){return m.Ud},"%%":function(){return"%"}};for(q in n)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),n[q](d)));q=Nb(c,
!1);if(q.length>b)return 0;H.set(q,a);return q.length-1},x:function(a){var b=Date.now()/1E3|0;a&&(M[a>>2]=b);return b}};
(function(){function a(f,g){e.asm=f.exports;Pa=e.asm.ia;Ra.unshift(e.asm.ga);U.nc.push(e.asm.ma);ta=g;w||ab()}function b(f){a(f.instance,f.module)}function c(f){return db().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){h("failed to asynchronously prepare wasm: "+g);C(g)})}var d={a:$c};w||$a();if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return h("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return sa||"function"!==typeof WebAssembly.instantiateStreaming||
bb()||R.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(R,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){h("wasm streaming compile failed: "+g);h("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.ga).apply(null,arguments)};
var ob=e._free=function(){return(ob=e._free=e.asm.ha).apply(null,arguments)},Xb=e.___errno_location=function(){return(Xb=e.___errno_location=e.asm.ja).apply(null,arguments)},L=e._malloc=function(){return(L=e._malloc=e.asm.ka).apply(null,arguments)},Xc=e._main=function(){return(Xc=e._main=e.asm.la).apply(null,arguments)};e._emscripten_tls_init=function(){return(e._emscripten_tls_init=e.asm.ma).apply(null,arguments)};
e._emscripten_current_thread_process_queued_calls=function(){return(e._emscripten_current_thread_process_queued_calls=e.asm.na).apply(null,arguments)};
var mb=e._emscripten_register_main_browser_thread_id=function(){return(mb=e._emscripten_register_main_browser_thread_id=e.asm.oa).apply(null,arguments)},Pc=e._emscripten_main_browser_thread_id=function(){return(Pc=e._emscripten_main_browser_thread_id=e.asm.pa).apply(null,arguments)},eb=e.__emscripten_do_dispatch_to_thread=function(){return(eb=e.__emscripten_do_dispatch_to_thread=e.asm.qa).apply(null,arguments)},Yc=e._emscripten_sync_run_in_main_thread_4=function(){return(Yc=e._emscripten_sync_run_in_main_thread_4=
e.asm.ra).apply(null,arguments)},qb=e._emscripten_main_thread_process_queued_calls=function(){return(qb=e._emscripten_main_thread_process_queued_calls=e.asm.sa).apply(null,arguments)},oc=e._emscripten_run_in_main_runtime_thread_js=function(){return(oc=e._emscripten_run_in_main_runtime_thread_js=e.asm.ta).apply(null,arguments)},tc=e.__emscripten_call_on_thread=function(){return(tc=e.__emscripten_call_on_thread=e.asm.ua).apply(null,arguments)};
e._emscripten_proxy_main=function(){return(e._emscripten_proxy_main=e.asm.va).apply(null,arguments)};
var lb=e.__emscripten_thread_init=function(){return(lb=e.__emscripten_thread_init=e.asm.wa).apply(null,arguments)},ac=e._memset=function(){return(ac=e._memset=e.asm.xa).apply(null,arguments)},V=e._pthread_self=function(){return(V=e._pthread_self=e.asm.ya).apply(null,arguments)},nb=e.___pthread_tsd_run_dtors=function(){return(nb=e.___pthread_tsd_run_dtors=e.asm.za).apply(null,arguments)},Nc=e._emscripten_get_global_libc=function(){return(Nc=e._emscripten_get_global_libc=e.asm.Aa).apply(null,arguments)},
Bb=e.__get_tzname=function(){return(Bb=e.__get_tzname=e.asm.Ba).apply(null,arguments)},Ab=e.__get_daylight=function(){return(Ab=e.__get_daylight=e.asm.Ca).apply(null,arguments)},zb=e.__get_timezone=function(){return(zb=e.__get_timezone=e.asm.Da).apply(null,arguments)},za=e.stackSave=function(){return(za=e.stackSave=e.asm.Ea).apply(null,arguments)},Aa=e.stackRestore=function(){return(Aa=e.stackRestore=e.asm.Fa).apply(null,arguments)},xa=e.stackAlloc=function(){return(xa=e.stackAlloc=e.asm.Ga).apply(null,
arguments)},sb=e._emscripten_stack_set_limits=function(){return(sb=e._emscripten_stack_set_limits=e.asm.Ha).apply(null,arguments)},Zc=e._memalign=function(){return(Zc=e._memalign=e.asm.Ia).apply(null,arguments)},pb=e.__emscripten_allow_main_runtime_queued_calls=1322616,ib=e.__emscripten_main_thread_futex=2920364;e.ccall=wa;e.cwrap=function(a,b,c,d){c=c||[];var f=c.every(function(g){return"number"===g});return"string"!==b&&f&&!d?va(a):function(){return wa(a,b,c,arguments,d)}};
e.setValue=function(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":H[a>>0]=b;break;case "i8":H[a>>0]=b;break;case "i16":Ja[a>>1]=b;break;case "i32":M[a>>2]=b;break;case "i64":T=[b>>>0,(S=b,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];M[a>>2]=T[0];M[a+4>>2]=T[1];break;case "float":Ka[a>>2]=b;break;case "double":La[a>>3]=b;break;default:C("invalid type for setValue: "+c)}};
e.writeAsciiToMemory=Ha;e.FS=Q;e.PThread=U;e.PThread=U;e.wasmMemory=E;e.ExitStatus=ca;var ad;function ca(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Za=function bd(){ad||cd();ad||(Za=bd)};
function cd(a){function b(){if(!ad&&(ad=!0,e.calledRun=!0,!ua)){Ua();w||Va(Sa);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(dd){var c=a,d=e._emscripten_proxy_main;c=c||[];var f=c.length+1,g=xa(4*(f+1));M[g>>2]=Ga(ia);for(var l=1;l<f;l++)M[(g>>2)+l]=Ga(c[l-1]);M[(g>>2)+f]=0;d(f,g)}if(!w){if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),Ta.unshift(c);Va(Ta)}}}a=a||ha;if(!(0<Xa))if(w)aa(e),Ua(),postMessage({cmd:"loaded"});else{if(!w){if(e.preRun)for("function"==
typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Wa();Va(Qa)}0<Xa||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=cd;function da(a,b){if(!b||!ub()||0!==a){if(!b&&w)throw postMessage({cmd:"exitProcess",returnCode:a}),new ca(a);if(!ub()){U.Nd();if(e.onExit)e.onExit(a);ua=!0}ja(a,new ca(a))}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var dd=!1;
e.noInitialRun&&(dd=!1);w&&(noExitRuntime=!1,U.rd());cd();


  return createFFmpegCore.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createFFmpegCore;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createFFmpegCore; });
else if (typeof exports === 'object')
  exports["createFFmpegCore"] = createFFmpegCore;
